### ISSUE TITLE
method to decode avro string

### ISSUE THREAD

**Issue by jigar87** [mtth/avsc#149]
Is there any method that takes avro string as input and returns decoded output?

**Comment by mtth** [comment]
What are the string's contents? If it's JSON-encoded data, you can call [`type.fromString`](https://github.com/mtth/avsc/wiki/API#typefromstringstr).

**Comment by jigar87** [comment]
Content of string is avro format content and I don't have schema details to
create type object.

So I am looking for something like createFileDecoder method which takes in
file content instead of file path.

On Feb 6, 2018 08:43, "Matthieu Monsch" <notifications@github.com> wrote:

What are the string's contents? If it's JSON-encoded data, you can call
type.fromString <https://github.com/mtth/avsc/wiki/API#typefromstringstr>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mtth/avsc/issues/149#issuecomment-363246811>, or mute
the thread

**Comment by mtth** [comment]
> So I am looking for something like createFileDecoder method which takes in file content instead of file path.

You can create a [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts) directly (it's used internally by `createFileDecoder`). Something like:

```javascript
// Convert your string data to a buffer, changing the encoding appropriately.
const buf = Buffer.from(stringData, 'binary');

// Decode the data. Here we simply print its contents.
const decoder = new avro.streams.BlockDecoder();
decoder.on('data', function (val) { console.log(val); }); // Print each value.
decoder.end(buf);
```

**Comment by jigar87** [comment]
Thanks Matthieu for prompt responses.

I tried creating the BlockDecoder as mentioned above but I am getting "out of range index" exception when it executes decoder.end(buf), belo is the stack trace,


`RangeError: out of range index
    at RangeError (native)
    at Tap.readFixed (C:\DEV\AzureFun\node_modules\avsc\lib\utils.js:545:12)
    at Tap.readBytes (C:\DEV\AzureFun\node_modules\avsc\lib\utils.js:562:15)
    at BytesType._read (C:\DEV\AzureFun\node_modules\avsc\lib\types.js:1095:57)
    at MapType._read (C:\DEV\AzureFun\node_modules\avsc\lib\types.js:1799:25)
    at RecordType.readHeader [as _read] (eval at <anonymous> (C:\DEV\AzureFun\node_modules\avsc\lib\types.js:2246:10), <anonymous>:6:8)
    at BlockDecoder._decodeHeader (C:\DEV\AzureFun\node_modules\avsc\lib\containers.js:175:28)
    at BlockDecoder._write (C:\DEV\AzureFun\node_modules\avsc\lib\containers.js:210:13)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5).

undefined:1
(function (f, ctx) { return function (d, cb) { return f(d, cb, ctx); }; })
                                                      ^
Error: RangeError: out of range index
    at RangeError (native)
    at Tap.readFixed (C:\DEV\AzureFun\node_modules\avsc\lib\utils.js:545:12)
    at Tap.readBytes (C:\DEV\AzureFun\node_modules\avsc\lib\utils.js:562:15)
    at BytesType._read (C:\DEV\AzureFun\node_modules\avsc\lib\types.js:1095:57)
    at MapType._read (C:\DEV\AzureFun\node_modules\avsc\lib\types.js:1799:25)
    at RecordType.readHeader [as _read] (eval at <anonymous> (C:\DEV\AzureFun\node_modules\avsc\lib\types.js:2246:10), <anonymous>:6:8)
    at BlockDecoder._decodeHeader (C:\DEV\AzureFun\node_modules\avsc\lib\containers.js:175:28)
    at BlockDecoder._write (C:\DEV\AzureFun\node_modules\avsc\lib\containers.js:210:13)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Error (native)
    at Object.handleUncaughtException (<anonymous>:1:55)
    at process.<anonymous> (C:\DEV\cellarise-package-manager\node_modules\azure-functions-core-tools\bin\azurefunctions\functions.js:17:17)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
`

**Comment by mtth** [comment]
The data doesn't contain a valid [Avro container file](https://avro.apache.org/docs/1.8.0/spec.html#Object+Container+Files) then. How is it generated? Were you able to open it with another tool or library?

**Comment by mtth** [comment]
Then it's probably an encoding issue: the string containing the data needs to be transformed to a buffer using the correct encoding. FTR `createFileDecoder` does essentially the same thing as the snippet above, just [opening the file path in `'binary'` mode](https://github.com/mtth/avsc/blob/master/lib/index.js#L74) instead of taking in a buffer directly.

**Comment by jigar87** [comment]
As you pointed out there seems to be some issues with encoding so instead of dealing with string I found a way to get the blob as readable stream, since that is exactly what was happening inside createFileDecoder.

Here is the solution to the problem "reading and decoding avro files created by event hub capture feature",

`const azureStorage = require('azure-storage');`
`const avro = require('avsc');`
`let blobSvc = azureStorage.createBlobService("connectionString");`
`function readBlobToText(blobSvc,blobBaseContainer, blobName){`
  `createStringDecoder(blobSvc,blobBaseContainer, blobName)`
   ` .on('data',(r)=>{`
   `   console.log(r);`
   ` });`
`}`
`function createStringDecoder(blobsvc, basecontainer, blobname){`
 ` return blobsvc.createReadStream(basecontainer, blobname).pipe(new avro.streams.BlockDecoder());`
`}`

## Usage example
`readBlobToText(blobSvc, 'baseContainer', 'folder1/folder2/folder3/output.avro');`

Matthieu, thank you very much for your help, appreciate it.

**Comment by mtth** [comment]
Great to hear you got it to work; thanks for the detailed update @jigar87!
