### ISSUE TITLE
no active channels

### ISSUE THREAD

**Issue by joaomilho** [mtth/avsc#161]
So I'm basically copying and pasting the basic getting started example, like so...

```js
avro.assembleProtocol('./LinkService.avdl', function(err, protocol) {
  // From which we can create our service.
  const service = avro.Service.forProtocol(protocol)

  const urlCache = new Map() // We'll use an in-memory map to store links.

  // We instantiate a server corresponding to our API and implement both calls.
  const server = service
    .createServer()
    .onCreateAlias(function(alias, url, cb) {
      if (urlCache.has(alias)) {
        cb(new Error('alias already exists'))
      } else {
        urlCache.set(alias, url) // Add the mapping to the cache.
        cb()
      }
    })
    .onExpandAlias(function(alias, cb) {
      cb(null, urlCache.get(alias))
    })

  const client = service.createClient({ server })

  // We first send a request to create an alias.
  client.createAlias('hn', 'https://news.ycombinator.com/', function(err) {
    console.log(err)
  })
})
```

Result is always:

```sh
Error: no active channels
    at Client._emitMessage$ (...node_modules/avsc/lib/services.js:612:17)
    at Client.emitMessage (...node_modules/avsc/lib/services.js:575:8)
    at Client.createAlias (eval at Client._createMessageHandler$ (...node_modules/avsc/lib/services.js:702:11), <anonymous>:4:15)
    at ...server.js:60:10
    at fetchImports (...node_modules/avsc/lib/specs.js:77:7)
    at ...node_modules/avsc/lib/specs.js:64:5
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

I'm quite sure I'm missing something and your help understanding would be highly appreciated. Thanks!

**Comment by mtth** [comment]
Hey @joaomilho, this was an issue with the documentation not being up-to-date. It should work if you just change the client creation code as follows:

```javascript
const client = service.createClient({buffering: true, server})
```

The enabled [`buffering`](https://github.com/mtth/avsc/wiki/API#servicecreateclientopts) option saves us from having to wait until a client channel becomes available (otherwise you'd typically wait on the `'channel'` event before sending any messages). I've updated the wiki to match, thank you for pointing it out!
