### ISSUE TITLE
Event Hub Capture - Error Invalid Union Index

### ISSUE THREAD

**Issue by JRiggenbach** [mtth/avsc#164]
We're attempting to use an Azure Function with a Blob Trigger written in Node.js.  We are triggering on Azure Event Hub Capture files.  We are using the following schema, as per the MS document, but also the same schema we get from the getSchema via the Apache Avro Tools:

``` "type" : "record",
 "name" : "EventData",
 "namespace" : "Microsoft.ServiceBus.Messaging",
 "fields" : [ {
   "name" : "SequenceNumber",
   "type" : "long"
 }, {
   "name" : "Offset",
   "type" : "string"
 }, {
   "name" : "EnqueuedTimeUtc",
   "type" : "string"
 }, {
   "name" : "SystemProperties",
   "type" : {
     "type" : "map",
     "values" : [ "long", "double", "string", "bytes" ]
   }
 }, {
   "name" : "Properties",
   "type" : {
     "type" : "map",
     "values" : [ "long", "double", "string", "bytes", "null" ]
   }
 }, {
   "name" : "Body",
   "type" : [ "null", "bytes" ]
 } ]
```
The Azure Function has the datatype set to Binary, as noted in this [issue](https://github.com/Azure/Azure-Functions/issues/215)
However, The function bombs out with the following error

```
2018-03-19T19:23:47.752 [Error,CaptureBlobTrigger] Error: invalid union index
    at WrappedUnionType._read (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:1454:11)
    at MapType._read (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:1801:25)
    at RecordType.readEventData [as _read] (eval at <anonymous> (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:2248:10), <anonymous>:8:8)
    at readValue (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:2817:17)
    at RecordType.Type.fromBuffer (D:\home\site\wwwroot\CaptureBlobTrigger\node_modules\avsc\lib\types.js:575:13)
    at module.exports (D:\home\site\wwwroot\CaptureBlobTrigger\index.js:40:28)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11612\bin\azurefunctions\functions.js:106:24
```
I'm too lazy to debug this myself...any suggestions?  Thanks.

**Comment by mtth** [comment]
Hard to say without any sample data. From the error message it looks like your data doesn't match the schema used to decode it (interestingly it looks like the first couple fields are decoded alright) or is corrupted.

**Comment by JRiggenbach** [comment]
That's fair. I can provide a sample. I'm going to say it's not corrupt because I have no issues writing a C# function to process the same across files. I would guess I'm doing something wrong moreso than an issue with your library, I just don't know what yet.

**Comment by JRiggenbach** [comment]
[194104.zip](https://github.com/mtth/avsc/files/1843290/194104.zip)
Attaching a .zip file that contains a sampel avro file that our EventHub is capturing to blob storage.  We can process this fine with the .net libraries, so we're doing something wrong with trying to use the avsc library to do the same.

**Comment by mtth** [comment]
Can you attach an uncompressed file and clarify how the data is encoded? Is it meant to contain the encoded bytes of a _single_ record of the schema above?

**Comment by RPS044** [comment]
@JRiggenbach @mtth is it solved ?

invalid union index: 4032 [object Object]"
