### ISSUE TITLE
Nested Aliases Don't Work

### ISSUE THREAD

**Issue by kyleboyer-optum** [mtth/avsc#217]
Schema:
```
{
  "type": "record",
  "name": "LogEvt",
  "namespace": "com.website.event.model",
  "fields": [
    {
      "name": "receivedTime",
      "type": "long",
      "doc": "Time the event was received by the application"
    },
    {
      "name": "application",
      "type": {
        "type": "record",
        "name": "AppData",
        "doc": "Information about an application",
        "fields": [
          {
            "name": "name",
            "type": "string",
            "doc": "Application Formal Name",
            "aliases" : ["Name"]
          }
        ]
      },
      "doc": "Information about the application that the event pertains to."
    }
  ]
}
```
Example JSON to be encoded to buffer:
```
{"receivedTime":1547566530431,"application":{"Name":"SampleApp"}}
```

I get the error:
Error: invalid "string": undefined
    at throwInvalidError (/Users/kboyer11/ness/alias-test/node_modules/avsc/lib/types.js:3015:9)
    at StringType._write (/Users/kboyer11/ness/alias-test/node_modules/avsc/lib/types.js:1070:5)
    at RecordType.writeAppData [as _write] (eval at RecordType._createWriter (/Users/kboyer11/ness/alias-test/node_modules/avsc/lib/types.js:2311:10), <anonymous>:4:6)
    at RecordType.writeLogEvt [as _write] (eval at RecordType._createWriter (/Users/kboyer11/ness/alias-test/node_modules/avsc/lib/types.js:2311:10), <anonymous>:5:6)
    at RecordType.Type.toBuffer (/Users/kboyer11/ness/alias-test/node_modules/avsc/lib/types.js:645:8)
    at Object.<anonymous> (/Users/kboyer11/ness/alias-test/index.js:30:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

**Comment by mtth** [comment]
Aliases are currently only used for reading binary-encoded data, it would be nice if they worked for JSON-encoded data too though. Note that it might not work exactly as your example suggests: aliases require both reader and writer schemas (to correctly [resolve types](http://avro.apache.org/docs/current/spec.html#Schema+Resolution)). So you would need a second schema with the field named `Name` in order to use it here. Is that acceptable for your use-case?

**Comment by mtth** [comment]
Alias resolution for JSON encoding is now available in [`@avro/types`](https://www.npmjs.com/package/@avro/types) (the types-only future version of `avsc`). It behaves consistently with binary encoding, for example:

```javascript
const {Type} = require('@avro/types');

const personType = Type.forSchema({
  name: 'Person',
  type: 'record',
  fields: [
    {name: 'name', type: 'string'},
  ],
});

const personWithAgeType = Type.forSchema({
  name: 'Person',
  type: 'record',
  fields: [
    {name: 'name', type: ['null', 'string'], default: null},
    {name: 'age', type: ['null', 'int'], default: null},
  ],
});

// The resolver via which we will can translate between the two types above (we
// can use the same resolver both for decoding binary and JSON data).
const resolver = personWithAgeType.createResolver(personType);

// Sample JSON encoded value for `personType`.
const personJSON = {name: 'Ann'};
// Decode it (note the resolver).
const personWithAge = personWithAgeType.fromJSON(personJSON, resolver);

console.log(personWithAge.toJSON()); // {name: {string: 'Ann'}, age: null}
```
