### ISSUE TITLE
Support gRPC

### ISSUE THREAD

**Issue by brandonros** [mtth/avsc#222]
```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const avro = require('avsc');
const https = require('https');

avro.assembleProtocol('./UserInfoService.avdl', (err, protocol) => {
  if (err) {
    throw err
  }

  const service = avro.Service.forProtocol(protocol);
  const client = service.createClient({
    buffering: true,
    transport: function (cb) {
      return https.request({method: 'POST', host: 'redacted', port: 31601})
        .on('response', function (res) { cb(null, res); })
        .on('error', function (err) { cb(err, null); });
    }
  });

  const body = service.type('redacted')
    .clone({
      username: {
        value: 'username'
      }
    })

  client.getPrimaryUserInfo(body, function(err, res) {
    console.log(err)
    console.log(res)
  })
})
```

```
Error: interrupted
    at Registry.<anonymous> (/Users/bros/Desktop/node_modules/avsc/lib/services.js:1865:19)
    at Array.forEach (<anonymous>)
    at Registry.clear (/Users/bros/Desktop/node_modules/avsc/lib/services.js:1864:26)
    at StatelessClientChannel.ClientChannel.destroy (/Users/bros/Desktop/node_modules/avsc/lib/services.js:912:14)
    at CallContext.<anonymous> (/Users/bros/Desktop/node_modules/avsc/lib/services.js:937:12)
    at onCompletion (/Users/bros/Desktop/node_modules/avsc/lib/services.js:1024:8)
    at StatelessClientChannel.<anonymous> (/Users/bros/Desktop/node_modules/avsc/lib/services.js:1014:7)
    at cb (/Users/bros/Desktop/node_modules/avsc/lib/services.js:1859:8)
    at /Users/bros/Desktop/node_modules/avsc/lib/services.js:1121:9
    at /Users/bros/Desktop/node_modules/avsc/lib/services.js:503:13
```

**Comment by brandonros** [comment]
I'm trying to hit a gRPC server that is using Avro and I have to admit, I am beyond lost.

**Comment by mtth** [comment]
Can you share the logs you get after running the code with the environment variable `NODE_DEBUG=avsc:services`?

Do you also have more information on the server you are calling? If you are speaking to a gRPC server, the transport you are using (standard HTTP POST request) might not be compatible.

**Comment by brandonros** [comment]
I am trying to speak to a gRPC server. Are there any examples of Avro over gRPC?

**Comment by mtth** [comment]
I'm not aware of any unfortunately. You would need to figure out how which request format the gRPC server expects (possibly leveraging existing gRPC libraries) and implement a custom transport (I can help with this part).

**Comment by brandonros** [comment]
https://github.com/salrashid123/grpc_curl

I found this and spent my entire day trying to get it to work, but the gRPC server (some Java/netty thing out of my control) throws grpc-status 2 (internal unknown error), which leads me to believe I am just formatting it incorrectly.

Avro + gRPC in node.js would be huge. Google shows there's...  nothing out there.

**Comment by brandonros** [comment]
```
OUTBOUND DATA: streamId=3 padding=0 endStream=true length=165 bytes=00000000a04f626a0104166176726f2e736368656d61b4017b2274797065223a227265636f7264222c226e616d65223a2250696e67222c226e616d6573706163...
```

```
 Objavro.schema´{"type":"record","name":"Ping","namespac
```

I have no idea how to get more than 64 bytes logged out of this Java avro client, but I find it amazing that there is no documentation of an example anywhere on the internet on what an Avro over gRPC frame looks like? Am I wrong/missing something?

**Comment by mtth** [comment]
Have you tried emailing the Avro mailing list (dev@avro.apache.org)? You could also file an issue in the [Avro JIRA](https://jira.apache.org/jira/projects/AVRO/issues/AVRO-1979?filter=allopenissues); it has an [Avro over gRPC features request](https://jira.apache.org/jira/browse/AVRO-2172), perhaps this is the same implementation as your server.

**Comment by brandonros** [comment]
```
const grpc = require('grpc')
const fs = require('fs')
const avro = require('avsc')
const hexdump = require('hexdump-nodejs')

const sendGrpcMessage = async (client, request, path) => {
  const encoder = () => request
  const decoder = (res) => res
  const metadata = {}
  const options = {}
  return new Promise((resolve, reject) => {
    client.makeUnaryRequest(path, encoder, decoder, metadata, options, (err, res) => {
      if (err) {
        return reject(err)
      }
      resolve(res)
    })
  })
}

const encodeMessage = (avroType, values) => {
  let opts = {
      codec: null,
      writeHeader: true
  };
  return new Promise((resolve, reject) => {
      let buffers = [];
      let encoder = new avro.streams.BlockEncoder(avroType, opts)
          .on('error', reject)
          .on('data', (value) => { buffers.push(value); })
          .on('end', () => { resolve(Buffer.concat(buffers)); });
      for (let v of values) {
          encoder.write(v);
      }
      encoder.end();
  })
}

const decodeMessage = (data) => {
  return new Promise((resolve, reject) => {
    let opts = {}
    let avroSchema;
    let events = [];
    let decoder = new avro.streams.BlockDecoder(opts)
        .on('error', reject)
        .on('metadata', (type) => { avroSchema = type; })
        .on('data', (value) => { events.push(value); })
        .on('end', () => { resolve({ avroSchema: avroSchema, data: events }); });
    decoder.write(data);
    decoder.end();
});
}

const run = async () => {
  const rootCert = fs.readFileSync('redacted.pem')
  const credentials = grpc.credentials.createSsl(rootCert)
  const client = new grpc.Client('redacted', credentials)
  const protocol = await new Promise((resolve, reject) => {
    avro.assembleProtocol('./PingService.avdl', (err, protocol) => {
      if (err) {
        return reject(err)
      }
      resolve(protocol)
    })
  })
  const pingType = protocol.types.find((type) => type.name === 'Ping')
  const message = await encodeMessage(pingType, [{}])
  const path = '/PingService/ping'
  const response = await sendGrpcMessage(client, message, path)
  console.log(await decodeMessage(response))
}

run()
.catch((err) => {
  console.error(err)
})
```

Working gRPC example for people who don't want to lose 15 hours of their life stringing together random Google searches.

**Comment by ChadKillingsworth** [comment]
@mtth Is there somewhere we can officially document this example? I realize node is not the primary use case, but it was not at all obvious on how to get even the basic ping working.

**Comment by crypticmind** [comment]
@brandonros example really helped me figure out how to operate with a gRPC service. 
I was able to simplify it down a bit and show a call that both receives and returns data.
```javascript
const grpc = require('grpc')
const avro = require('avsc')

const sendGrpcMessage = async (client, request, path) => {
    const encoder = () => request
    const decoder = (res) => res
    const args = null
    const metadata = null
    const options = null
    return new Promise((resolve, reject) => {
        client.makeUnaryRequest(path, encoder, decoder, args, metadata, options, (err, res) => {
            if (err) {
                return reject(err)
            }
            resolve(res)
        })
    })
}

const run = async () => {
    const credentials = grpc.credentials.createInsecure();
    const client = new grpc.Client('localhost:12345', credentials)
    const protocol = await new Promise((resolve, reject) => {
        avro.assembleProtocol('protocol.avdl', (err, protocol) => {
            if (err) {
                return reject(err)
            }
            resolve(protocol)
        })
    })
    const registry = {};
    avro.Type.forSchema(protocol.types, { registry });
    const RequestType = registry['RequestType'];
    const ResponseType = registry['ResponseType'];
    const path = `/${protocol.namespace}.${protocol.protocol}/MessageName`;
    const request = { foo: '123', bar: true };
    const outgoing = RequestType.toBuffer(request);
    const incoming = await sendGrpcMessage(client, outgoing, path);
    const response = ResponseType.decode(incoming, registry);
    console.log(response)
}

run().catch((err) => {
    console.error(err)
})
```
