### ISSUE TITLE
Cannot parse avro schema generated by go backend

### ISSUE THREAD

**Issue by brianc** [mtth/avsc#236]
Howdy!  Apologies if this has been asked before, but I'm having an issue parsing an avro schema from a backend a colleague is writing in golang.  In their code they're able to build the schema and stream avro and parse it, but when consuming the same stream in node I get the following error:

```
/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:177
    throw new Error(f('undefined type name: %s', schema));
    ^

Error: undefined type name: main.Map
    at Function.Type.forSchema (/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:177:11)
    at new Field (/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:2775:20)
    at RecordType.<anonymous> (/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:2103:17)
    at Array.map (<anonymous>)
    at new RecordType (/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:2102:45)
    at /Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:220:14
    at Function.Type.forSchema (/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:221:7)
    at /Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:208:19
    at Array.map (<anonymous>)
    at Function.Type.forSchema (/Users/bcarlson/src/trace-viewer/node_modules/avsc/lib/types.js:207:24)
```

Here's some self contained code to reproduce the issue:

```js
const avsc = require('avsc')
const schema = ["null", {
  "name": "Delay", "namespace": "main", "type": "record",
  "fields": [{
    "name": "ts", "type": "long"
  }, {
    "name": "extra", "type": "map", "values": "string"
  }],
}]

avsc.Type.forSchema(schema);
```

We were thinking possibly this is a bug w/ the avsc library, but I'm not sure...maybe we're generating the avro schema wrong?  Any pointers on documentation or stuff we could look at to get to the bottom of things?

**Comment by mtth** [comment]
Hey @brianc! This schema is invalid. The map's `values` should belong to the type rather than the field. Breaking it down:

```javascript
[ // Union
  'null',
  { // Record
    name: 'Delay',
    namespace: 'main',
    type: 'record',
    fields: [
      { // Field
        name: 'ts',
        type: 'long',
      },
      { // Field
        name: 'extra',
        type: { // (Field) type
          type: 'map',
          values: 'string', // The values entry belongs here, not in the outer field.
        },
      },
    ],
  },
]
```

Using this schema should work; please reopen if not. (The [specification](http://avro.apache.org/docs/current/spec.html) also has more information on schema declaration if you are curious.)
