### ISSUE TITLE
Schema not matching after deserialization

### ISSUE THREAD

**Issue by xandel434** [mtth/avsc#241]
We have a Java project that serializes a schema but that same schema fails to get deserialize in a node project. 

```
/Users/user/Workspace/project/project-name/node_modules/avsc/lib/types.js:1306
    throw new Error(f('invalid union index: %s', index));
          ^
Error: invalid union index: -1
    at UnwrappedUnionType._read (/Users/user/Workspace/project/project-name/node_modules/avsc/lib/types.js:1306:11)
    at RecordType.readEnterpriseEventEnvelopeRecord [as _read] (eval at RecordType._createReader (/Users/user/Workspace/project/project-name/node_modules/avsc/lib/types.js:2265:10), <anonymous>:8:8)
    at RecordType.readContentChange [as _read] (eval at RecordType._createReader (/Users/user/Workspace/project/project-name/node_modules/avsc/lib/types.js:2265:10), <anonymous>:5:8)
    at readValue (/Users/user/Workspace/project/project-name/node_modules/avsc/lib/types.js:2870:17)
    at RecordType.Type.fromBuffer (/Users/user/Workspace/project/project-name/node_modules/avsc/lib/types.js:589:13)
    at decodeMessage (/Users/ufi163/Workspace/CloudApparatus/cloud-machine-v2/dist/apps/sdp-consumer/webpack:/apps/sdp-consumer/src/consumer.ts:80:19)
    at Consumer.consumer.on (/Users/ufi163/Workspace/CloudApparatus/cloud-machine-v2/dist/apps/sdp-consumer/webpack:/apps/sdp-consumer/src/consumer.ts:51:24)
    at emitOne (events.js:116:13)
    at Consumer.emit (events.js:211:7)
    at /Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/client.js:212:16
    at Object.<anonymous> (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:236:20)
    at Object.self.tap (/Users/user/Workspace/project/project-name/node_modules/binary/index.js:248:12)
    at decodeMessageSet (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:198:8)
    at Object.<anonymous> (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:147:26)
    at Object.self.tap (/Users/user/Workspace/project/project-name/node_modules/binary/index.js:248:12)
    at Object.decodePartitions (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:141:8)
    at Object.self.loop (/Users/user/Workspace/project/project-name/node_modules/binary/index.js:267:16)
    at Object.<anonymous> (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:68:8)
    at Object.self.loop (/Users/user/Workspace/project/project-name/node_modules/binary/index.js:267:16)
    at _decodeFetchResponse (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:132:6)
    at /Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/protocol/protocol.js:102:12
    at KafkaClient.Client.handleReceivedData (/Users/user/Workspace/project/project-name/node_modules/kafka-node/lib/client.js:782:20)
```

Help?

**Comment by mtth** [comment]
Hard to say much without any information on the schema or data. Can you share a snippet reproducing the error?

**Comment by xandel434** [comment]
```
{
    "type": "record",
    "name": "ContentChange",
    "namespace": "com.project.team.acro",
    "doc": "Explain here",
    "fields": [
        {
            "name": "enterpriseEventEnvelope",
            "doc": "Defines the enterprise-wide information that is contained in all messages. You should not edit this portion of the schema.",
            "type": {
                "type": "record",
                "name": "EnterpriseEventEnvelopeRecord",
                "fields": [
                    {
                        "name": "eventId",
                        "type": "string",
                        "default": "",
                        "doc": "Global unique identifier assigned to each event. Do not edit this field."
                    },
                    {
                        "name": "eventPrefix",
                        "type": "string",
                        "default": "",
                        "doc": "The capability of the Event. Do not edit this field."
                    },
                    {
                        "name": "eventQualifier",
                        "type": "string",
                        "default": "",
                        "doc": "Qualifiers determined by the respective domain owners based on the capability being delivered. Do not edit this field."
                    },
                    {
                        "name": "eventAction",
                        "type": [
                            "null",
                            {
                                "type": "enum",
                                "name": "actionTypes",
                                "symbols": [
                                    "Updated",
                                    "Created",
                                    "Requested",
                                    "Deleted",
                                    "Verified",
                                    "Received",
                                    "Completed",
                                    "Failed",
                                    "Abandoned"
                                ]
                            }
                        ],
                        "default": null,
                        "doc": "A verb indicating what happened that resulted in the Event being triggered. Do not edit this field."
                    },
                    {
                        "name": "eventOccurrenceTimestamp",
                        "type": "string",
                        "default": "",
                        "doc": "Local time at which the event occurred. Do not edit this field."
                    },
                    {
                        "name": "providerId",
                        "type": "string",
                        "default": "",
                        "doc": "Unique ID assigned to source application/capability. Do not edit this field."
                    },
                    {
                        "name": "correlationId",
                        "type": [
                            "null",
                            "string"
                        ],
                        "default": null,
                        "doc": "The eventId of the event which caused this event. Do not edit this field."
                    },
                    {
                        "name": "referenceIds",
                        "type": [
                            "null",
                            {
                                "type": "record",
                                "name": "ReferenceIdsRecord",
                                "fields": []
                            }
                        ],
                        "default": null,
                        "doc": "A selection of defined reference identifiers. Do not edit this field."
                    },
                    {
                        "name": "domainPayloadVersion",
                        "type": "string",
                        "default": "",
                        "doc": "The domain payload version. Do not edit this field."
                    },
                    {
                        "name": "eventDataQuality",
                        "type": [
                            "null",
                            {
                                "type": "record",
                                "name": "EventDataQualityAttributesRecord",
                                "fields": [
                                    {
                                        "name": "executedRuleSetId",
                                        "doc": "The id for the set of rules used to validate the data. Do not edit this field.",
                                        "type": "string",
                                        "default": ""
                                    },
                                    {
                                        "name": "failedRuleIds",
                                        "type": [
                                            "null",
                                            {
                                                "type": "array",
                                                "items": "string"
                                            }
                                        ],
                                        "default": null,
                                        "doc": "Rules that got executed successfully and failed the condition for the rule. Do not edit this field."
                                    },
                                    {
                                        "name": "errorRuleIds",
                                        "type": [
                                            "null",
                                            {
                                                "type": "array",
                                                "items": "string"
                                            }
                                        ],
                                        "default": null,
                                        "doc": "Rules that have exception/error while executing. Do not edit this field."
                                    }
                                ]
                            }
                        ],
                        "default": null,
                        "doc": "Result of business context check executed by producer. Do not edit this field."
                    }
                ]
            }
        },
        {
            "name": "domainPayload",
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "DomainPayLoadRecord",
                    "fields": [
                        {
                            "name": "channelId",
                            "type": "string",
                            "doc": "The HST configuration identifier for the channel.",
                            "default": ""
                        },
                        {
                            "name": "channelName",
                            "type": "string",
                            "doc": "The friendly name. Example: learn-grow",
                            "default": ""
                        },
                        {
                            "name": "eventType",
                            "type": [
                                "null",
                                {
                                    "type": "enum",
                                    "name": "eventType",
                                    "symbols": [
                                        "Channel",
                                        "Content"
                                    ]
                                }
                            ],
                            "doc": "Enum of either \"Channel\" or \"Content\" indicating if the content change was made at the channel level or content level.",
                            "default": null
                        },
                        {
                            "name": "channelUrl",
                            "type": "string",
                            "doc": "The base URL of the site.",
                            "default": ""
                        },
                        {
                            "name": "pagesChanged",
                            "type": {
                                "name": "PagesChangedArray",
                                "type": "array",
                                "items": {
                                    "name": "PagesChangedArrayRecord",
                                    "type": "record",
                                    "fields": [
                                        {
                                            "name": "pageId",
                                            "type": "string",
                                            "doc": "Example: c9f06d11-8a4f-44d7-a517-fa0ace60c147"
                                        },
                                        {
                                            "name": "pageName",
                                            "type": "string",
                                            "doc": "Example: Learn and Grow"
                                        },
                                        {
                                            "name": "pageUrl",
                                            "type": "string",
                                            "doc": "The page path relative to the base channel URL."
                                        },
                                        {
                                            "name": "changeType",
                                            "type": [
                                                {
                                                    "type": "enum",
                                                    "name": "changeType",
                                                    "symbols": [
                                                        "New",
                                                        "Delete",
                                                        "Modified"
                                                    ]
                                                }
                                            ],
                                            "doc": "This field indicates the type of page change. New indicates that this is a new page that was just created. Delete indicates that the page was deleted. Modified indicates a change to an existing page."
                                        }
                                    ]
                                }
                            },
                            "doc": "A collection of page routes that should be built.",
                            "default": []
                        }
                    ]
                }
            ],
            "default": null,
            "doc": "The application payload."
        }
    ]
}
```

**Comment by xandel434** [comment]
@mtth it's a pretty complex schema. However, with a Java deserializer I am able to get the json. I have access to the Java code as well, let me know if you need more context.

**Comment by xandel434** [comment]
```
function decodeMessage(messageSchema: any, message: string | Buffer) {
  console.log(messageSchema);
  
  const avroType = avsc.Type.forSchema(messageSchema, {
    logicalTypes: { 'timestamp-millis': AvroDateType },
  });

  return avroType.fromBuffer(message);
}
```

**Comment by xandel434** [comment]
Stack trace
```
```
/Users/user/Workspace/team/project/node_modules/avsc/lib/types.js:1306
    throw new Error(f('invalid union index: %s', index));
          ^
Error: invalid union index: -1
    at UnwrappedUnionType._read (/Users/user/Workspace/team/project/node_modules/avsc/lib/types.js:1306:11)
    at RecordType.readEnterpriseEventEnvelopeRecord [as _read] (eval at RecordType._createReader (/Users/user/Workspace/team/project/node_modules/avsc/lib/types.js:2265:10), <anonymous>:8:8)
    at RecordType.readContentChange [as _read] (eval at RecordType._createReader (/Users/user/Workspace/team/project/node_modules/avsc/lib/types.js:2265:10), <anonymous>:5:8)
    at readValue (/Users/user/Workspace/team/project/node_modules/avsc/lib/types.js:2870:17)
    at RecordType.Type.fromBuffer (/Users/user/Workspace/team/project/node_modules/avsc/lib/types.js:589:13)
    at decodeMessage (/Users/user/Workspace/team/project/dist/apps/sdp-consumer/webpack:/apps/sdp-consumer/src/consumer.ts:85:19)
    at Consumer.rxjs_1.Observable.create.consumer.on (/Users/user/Workspace/team/project/dist/apps/sdp-consumer/webpack:/apps/sdp-consumer/src/consumer.ts:54:24)
    at emitOne (events.js:116:13)
    at Consumer.emit (events.js:211:7)
    at /Users/user/Workspace/team/project/node_modules/kafka-node/lib/client.js:212:16
    at Object.<anonymous> (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:236:20)
    at Object.self.tap (/Users/user/Workspace/team/project/node_modules/binary/index.js:248:12)
    at decodeMessageSet (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:198:8)
    at Object.<anonymous> (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:147:26)
    at Object.self.tap (/Users/user/Workspace/team/project/node_modules/binary/index.js:248:12)
    at Object.decodePartitions (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:141:8)
    at Object.self.loop (/Users/user/Workspace/team/project/node_modules/binary/index.js:267:16)
    at Object.<anonymous> (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:68:8)
    at Object.self.loop (/Users/user/Workspace/team/project/node_modules/binary/index.js:267:16)
    at _decodeFetchResponse (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:132:6)
    at /Users/user/Workspace/team/project/node_modules/kafka-node/lib/protocol/protocol.js:102:12
    at KafkaClient.Client.handleReceivedData (/Users/user/Workspace/team/project/node_modules/kafka-node/lib/client.js:782:20)```
```

**Comment by xandel434** [comment]
Could it be because the Java code is using `1.8.2` Avro specification while this package is for `1.8.1` or am I mistaken? Also, thank you for looking at this issue.

**Comment by mtth** [comment]
Avro `1.8.1` and `1.8.2` should have compatible encodings. The above schema is valid; I suspect the issue is caused either by a prefix in the data (e.g. [a Kafka header](https://github.com/mtth/avsc/issues/22#issuecomment-166350702)) or by an upstream encoding issue leading to corrupt data. Can you check if either seems likely?

**Comment by xandel434** [comment]
I can verify the header issue but can you direct me on how to verify the encoding issue? Not really sure how to do that

**Comment by mtth** [comment]
You could compare the bytes directly after serialization on the Java side and right before deserialization in node.

**Comment by xandel434** [comment]
> Avro `1.8.1` and `1.8.2` should have compatible encodings. The above schema is valid; I suspect the issue is caused either by a prefix in the data (e.g. [a Kafka header](https://github.com/mtth/avsc/issues/22#issuecomment-166350702)) or by an upstream encoding issue leading to corrupt data. Can you check if either seems likely?

I think this is what's happening but I'm trying to do the other way. I'm not writing but reading. Deserializing. How would I go about doing that? @mtth I appreciate you taking the time to reply.

**Comment by xandel434** [comment]
What I got from Kafka
```
�8event ID Map test 1561388909.2019-06-24T15:08:29.947H55c71b9d-f8ff-4118-b7b3-07b84c20b57aH324ad799-ca80-4c99-b63f-821beb2a410bcard,http://localhost:8080/H78497126-5fbc-47fb-88e9-16955f4b4db62test-single-column-layout
/test
```

What was sent to Kafka
```
Objavro.schema�J{"type":"record","name":"ContentChange","namespace":"com.team.project.wcm","doc":"When content changes.","fields":[{"name":"enterpriseEventEnvelope","type":{"type":"record","name":"EnterpriseEventEnvelopeRecord","fields":[{"name":"eventId","type":"string","doc":"Global unique identifier assigned to each event. Do not edit this field.","default":""},{"name":"eventPrefix","type":"string","doc":"The capability of the Event. Do not edit this field.","default":""},{"name":"eventQualifier","type":"string","doc":"Qualifiers determined by the respective domain owners based on the capability being delivered. Do not edit this field.","default":""},{"name":"eventAction","type":["null",{"type":"enum","name":"actionTypes","symbols":["Updated","Created","Requested","Deleted","Verified","Received","Completed","Failed","Abandoned"]}],"doc":"A verb indicating what happened that resulted in the Event being triggered. Do not edit this field.","default":null},{"name":"eventOccurrenceTimestamp","type":"string","doc":"Local time at which the event occurred. Do not edit this field.","default":""},{"name":"providerId","type":"string","doc":"Unique ID assigned to source application/capability. Do not edit this field.","default":""},{"name":"correlationId","type":["null","string"],"doc":"The eventId of the event which caused this event. Do not edit this field.","default":null},{"name":"referenceIds","type":["null",{"type":"record","name":"ReferenceIdsRecord","fields":[]}],"doc":"A selection of defined reference identifiers. Do not edit this field.","default":null},{"name":"domainPayloadVersion","type":"string","doc":"The domain payload version. Do not edit this field.","default":""},{"name":"eventDataQuality","type":["null",{"type":"record","name":"EventDataQualityAttributesRecord","fields":[{"name":"executedRuleSetId","type":"string","doc":"The id for the set of rules used to validate the data. Do not edit this field.","default":""},{"name":"failedRuleIds","type":["null",{"type":"array","items":"string"}],"doc":"Rules that got executed sucessfully and failed the condition for the rule. Do not edit this field.","default":null},{"name":"errorRuleIds","type":["null",{"type":"array","items":"string"}],"doc":"Rules that have exception/error while executing. Do not edit this field.","default":null}]}],"doc":"Result of business context check executed by producer. Do not edit this field.","default":null}]},"doc":"Defines the enterprise-wide information that is contained in all messages. You should not edit this portion of the schema."},{"name":"domainPayload","type":["null",{"type":"record","name":"DomainPayLoadRecord","fields":[{"name":"channelId","type":"string","doc":"The HST configuration identifier for the channel. Example: d6ea9a5d-695c-4aa3-b580-e8402d4840ae","default":""},{"name":"channelName","type":"string","doc":"The friendly name of the HST channel configuration. Example: learn-grow","default":""},{"name":"eventType","type":["null",{"type":"enum","name":"eventType","symbols":["Channel","Content"]}],"doc":"Enum of either \"Channel\" or \"Content\" indicating if the content change was made at the channel level or content level.","default":null},{"name":"channelUrl","type":"string","doc":"The base URL of the site.","default":""},{"name":"pagesChanged","type":{"type":"array","items":{"type":"record","name":"PagesChangedArrayRecord","fields":[{"name":"pageId","type":"string","doc":"The unique ID of the page. Example: c9f06d11-8a4f-44d7-a517-fa0ace60c147"},{"name":"pageName","type":"string","doc":"The page name in the CMS. Example: Learn and Grow"},{"name":"pageUrl","type":"string","doc":"The page path relative to the base channel URL. Example: /learn-grow"},{"name":"changeType","type":[{"type":"enum","name":"changeType","symbols":["New","Delete","Modified"]}],"doc":"This field indicates the type of page change. New indicates that this is a new page that was just created. Delete indicates that the page was deleted. Modified indicates a change to an existing page."}]}},"doc":"A collection of page routes that should be built as a result of content changes in the CMS.","default":[]}]}],"doc":"The application payload.","default":null}]}��OV9P�ޟ�mk���8event ID Map test 1561389541.2019-06-24T15:19:01.375H4932206b-8cfc-486d-8cc3-5e8cb5b0178ccard,http://localhost:8080/He5e29897-7eec-4c7e-b794-6dbd464de2602test-single-column-layout
/test��OV9P�ޟ�mk��
```

**Comment by mtth** [comment]
There's almost certainly a prefix in the data you're receiving from Kafka: the first field in the record is the `eventId` (likely encoded as `8event ID Map test 1561388909`: `8` is the binary encoding of 28, the length of the ID) but it's preceded by 5 bytes (we can't see their value, just their presence with the `�` characters). Can you try decoding after stripping the prefix (e.g. via 1buf.slice(5)`)?

**Comment by xandel434** [comment]
I think you just fixed my issue @mtth. Will confirm after testing further but as of now, slicing the buffer is all I needed. Also, thank you for taking the time to explain the reasoning to me. 

Closing.

**Comment by RPS044** [comment]
@mtth @xandel434 is it solved?
