### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: invalid "long"

### ISSUE THREAD

**Issue by markdthompson** [mtth/avsc#244]
Hello Matthieu Monsch,
I'm getting the following error when I run 'var buf = type.toBuffer(message.value);' while reading a message using kafka-node as a consumer. Any recommendations?

(node:83129) UnhandledPromiseRejectionWarning: Error: invalid "long": undefined
    at throwInvalidError (/Users/markthompson/Projects/Satisfi/Microservices/node_modules/avsc/lib/types.js:3023:9)
    at LongType._write (/Users/markthompson/Projects/Satisfi/Microservices/node_modules/avsc/lib/types.js:921:5)
    at RecordType.writeRecord$ [as _write] (eval at RecordType._createWriter (/Users/markthompson/Projects/Satisfi/Microservices/node_modules/avsc/lib/types.js:2318:10), <anonymous>:4:6)
    at RecordType.Type.toBuffer (/Users/markthompson/Projects/Satisfi/Microservices/node_modules/avsc/lib/types.js:652:8)
    at Consumer.<anonymous> (/Users/markthompson/Projects/Satisfi/Microservices/queue_mgr_consumer.js:23:20)
    at Consumer.emit (events.js:182:13)
    at /Users/markthompson/Projects/Satisfi/Microservices/node_modules/kafka-node/lib/baseClient.js:68:16
    at decodeMessageSet (/Users/markthompson/Projects/Satisfi/Microservices/node_modules/kafka-node/lib/protocol/protocol.js:308:15)
    at enqueue (/Users/markthompson/Projects/Satisfi/Microservices/node_modules/kafka-node/lib/protocol/protocol.js:407:15)
    at /Users/markthompson/Projects/Satisfi/Microservices/node_modules/async/dist/async.js:3880:24

**Comment by mtth** [comment]
It looks like the input data (`message.value`) doesn't match the type's schema. You can use [this error hook](https://gist.github.com/mtth/fe006b5b001beeaed95f#file-collect-js) to help you figure out exactly where the mismatch happens ([more information here](https://github.com/mtth/avsc/wiki/API#typeisvalidval-opts)).
