### ISSUE TITLE
Invalid record causes following messages to fail

### ISSUE THREAD

**Issue by gasserus** [mtth/avsc#266]
If I send an invalid record all messages which follow after that fail.

The message sent:
```
Objavro.schema� {
```
```
[79, 98, 106, 1, 2, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97, 239, 191, 189, 32, 123]
```

The exception, which is ok because the message is invalid.
```
{ RangeError: Index out of range
    at Buffer.copy (buffer.js:636:12)
    at Tap.readFixed (...\node_modules\avsc\lib\utils.js:571:12)
    at Tap.readBytes (...\node_modules\avsc\lib\utils.js:588:15)
    at BytesType._read (...\node_modules\avsc\lib\types.js:1120:57)
    at MapType._read (...\node_modules\avsc\lib\types.js:1824:25)
    at RecordType.readHeader [as _read] (eval at RecordType._createReader (...\node_modules\avsc\lib\types.js:2271:10), <anonymous>:6:8)
    at BlockDecoder._decodeHeader (...\node_modules\avsc\lib\containers.js:178:28)
    at BlockDecoder._write (...\node_modules\avsc\lib\containers.js:219:13)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5) code: 'ERR_INDEX_OUT_OF_RANGE' }
```

Then a valid message is sent. Here I get an error which I didn't expect.
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at BlockDecoder._decodeHeader (...\node_modules\avsc\lib\containers.js:192:23)
    at BlockDecoder._write (...\node_modules\avsc\lib\containers.js:219:13)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at BlockDecoder.Writable.write (_stream_writable.js:299:11)
    at BlockDecoder.Writable.end (_stream_writable.js:584:10)
    at createStringDecoder (...\CosmicEventHubTrigger\index.js:5:13)
    at Promise (...\CosmicEventHubTrigger\index.js:13:9)
    at new Promise (<anonymous>)
```

---
Sample to reproduce:
```
const avro = require('avsc');

// Invalid records
try {
    let invalidData = Buffer.from([79, 98, 106, 1, 2, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97, 239, 191, 189, 32, 123]);
    var invalidDataDecoder = new avro.streams.BlockDecoder();
    invalidDataDecoder.end(invalidData);
}
catch (err) {
    console.log("InvalidData", err);
}

// Valid record
try {
    let validData = Buffer.from([79, 98, 106, 1, 2, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97, 146, 3, 123, 34, 116, 121, 112, 101, 34, 58, 34, 114, 101, 99, 111, 114, 100, 34, 44, 34, 110, 97, 109, 101, 34, 58, 34, 85, 115, 101, 114, 34, 44, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, 34, 58, 34, 101, 120, 97, 109, 112, 108, 101, 46, 97, 118, 114, 111, 34, 44, 34, 102, 105, 101, 108, 100, 115, 34, 58, 91, 123, 34, 110, 97, 109, 101, 34, 58, 34, 110, 97, 109, 101, 34, 44, 34, 116, 121, 112, 101, 34, 58, 34, 115, 116, 114, 105, 110, 103, 34, 125, 44, 123, 34, 110, 97, 109, 101, 34, 58, 34, 102, 97, 118, 111, 114, 105, 116, 101, 95, 110, 117, 109, 98, 101, 114, 34, 44, 34, 116, 121, 112, 101, 34, 58, 91, 34, 105, 110, 116, 34, 44, 34, 110, 117, 108, 108, 34, 93, 125, 44, 123, 34, 110, 97, 109, 101, 34, 58, 34, 102, 97, 118, 111, 114, 105, 116, 101, 95, 99, 111, 108, 111, 114, 34, 44, 34, 116, 121, 112, 101, 34, 58, 91, 34, 115, 116, 114, 105, 110, 103, 34, 44, 34, 110, 117, 108, 108, 34, 93, 125, 93, 125, 0, 242, 138, 77, 126, 90, 123, 129, 64, 199, 75, 131, 117, 72, 246, 62, 225, 2, 26, 8, 116, 101, 115, 116, 0, 246, 1, 0, 6, 97, 115, 100, 242, 138, 77, 126, 90, 123, 129, 64, 199, 75, 131, 117, 72, 246, 62, 225]);
    var validDataDecoder = new avro.streams.BlockDecoder();
    validDataDecoder.end(validData);
}
catch (err) {
    console.log("ValidData", err);
}
```

---

I'm not very familiar with this library, but as far as I see the problem is that the calculated length is a negative number (-34058232).
This number is then used in the readFixed method, where it tries to allocate a negative number of bytes.
This negative number is then also set as _pos in the BufferPool, which is causing following messages to fail.
https://github.com/mtth/avsc/blob/497c410a4911e12a32b88fbdd451b1fa52f2a2c8/lib/utils.js#L564-L573

**Comment by mtth** [comment]
Thanks for the great report! You're correct, this was due to `BufferPool`'s state becoming corrupted after this particular type of invalid data. This should be fixed in `5.4.15` which was just released. Please reopen if not.
