### ISSUE TITLE
DateType example throws error

### ISSUE THREAD

**Issue by john-aws** [mtth/avsc#286]
The 'Logical types' example implementing `DateType` fails as follows:

```
node_modules/avsc/lib/types.js:3023
  throw new Error(f('invalid %j: %j', type.schema(), val));
  ^

Error: invalid "long": "2015-11-05T19:38:05.000Z"
    at throwInvalidError (node_modules/avsc/lib/types.js:3023:9)
    at LongType._write (node_modules/avsc/lib/types.js:921:5)
    at RecordType.writeTransaction [as _write] (eval at RecordType._createWriter (node_modules/avsc/lib/types.js:2318:10), <anonymous>:5:6)
    at RecordType.Type.toBuffer (node_modules/avsc/lib/types.js:652:8)
    at Object.<anonymous> (avro_test.js:26:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

The code I am using is verbatim from the github [Advance Usage README](https://github.com/mtth/avsc/wiki/Advanced-usage) and the [DateType gist](https://gist.github.com/mtth/1aec40375fbcb077aee7#file-date-js):

```js
const avro = require('avsc');
const DateType = require('./date_type.js');

const schema = {
  name: 'Transaction',
  type: 'record',
  fields: [
    { name: 'amount', type: 'int' },
    { name: 'time', type: { type: 'long', logicalType: 'timestamp-millis' } }
  ]
};

const type = avro.Type.forSchema(
  schema,
  { logicalTypes: { 'timestamp-millis': DateType } }
);

// We create a new transaction.
const transaction = {
  amount: 32,
  time: new Date('Thu Nov 05 2015 11:38:05 GMT-0800 (PST)')
};

// Our type is able to directly serialize it, including the date.
const buf = type.toBuffer(transaction);

// And we can get the date back just as easily.
const date = type.fromBuffer(buf).time;
```

**Comment by john-aws** [comment]
This appears to be because the following test fails in `LongType.prototype._write`:

```
typeof val != 'number'
```

And that's because `val` is an object, not a number. Note: `val` at this point prints as `2015-11-05T19:38:05.000Z`.

**Comment by john-aws** [comment]
OK, I know what is going wrong. User error. There is no default export from date_type.js so the effective value of `DateType = require('./date_type.js')` is empty object, when it should be a class derived from `avro.types.LogicalType` (specifically `DateType`). And because JavaScript eschews type safety this doesn't surface as an error.

Adding the following to `date_type.js` resolves this:

```js
module.exports=DateType;
```
