### ISSUE TITLE
Golang Avro serialization vs Javascript avsc.fromBuffer

### ISSUE THREAD

**Issue by inm-rmorales** [mtth/avsc#337]
Good afternoon,

I would like to know if it is possible to assist me with a current issue.
I have a client application that send me a avro serialized object converted in base64, using the following schema:

```
{
  "namespace": "cardstack.avro",
  "type": "record",
  "name": "Cursor",
  "fields": [
    {"name":"type","type":"string", "default": "ps"},
    {"name":"card_0","type":"long", "default": 0},
    {"name":"card_1","type":"long", "default": 0},
    {"name":"card_2","type":"long", "default": 0},
    {"name":"card_3","type":"long", "default": 0},
    {"name":"section_0","type":"long", "default": 0},
    {"name":"section_1","type":"long", "default": 0},
    {"name":"section_2","type":"long", "default": 0},
    {"name":"section_3","type":"long", "default": 0},
    {"name":"page","type":"int"},
    {"name":"size","type":"int"}
  ]
}
```
The client application is in golang. And everytime I tried to decode the object that is sent, I get an error:

```
[Nest] 104856   - 2021-02-26 18:47:32   [ExceptionsHandler] trailing data +6407ms
Error: trailing data
    at RecordType.Type.fromBuffer (C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\avsc\lib\types.js:597:11)
    at Object.cursorDecodeAvsc (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\util\home.helper.js:59:27)    at HomeService.search (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.service.js:51:39)
    at HomeService.cardsGenerator (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.service.js:169:39)    at HomeService.homeFiltered (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.service.js:374:28)  
    at HomeController.FilteredCards (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.v1.controller.js:30:39)
    at C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\@nestjs\core\router\router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at async C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\@nestjs\core\router\router-proxy.js:9:17  
here
```
using the following code:

```
function cursorDecodeAvsc(): avroSchema {
  const schema = Type.forSchema({
    namespace: 'cardstack.avro',
    type: 'record',
    name: 'Cursor',
    fields: [
      { name: 'type', type: 'string', default: 'ps' },
      { name: 'card_0', type: 'long', default: 0 },
      { name: 'card_1', type: 'long', default: 0 },
      { name: 'card_2', type: 'long', default: 0 },
      { name: 'card_3', type: 'long', default: 0 },
      { name: 'section_0', type: 'long', default: 0 },
      { name: 'section_1', type: 'long', default: 0 },
      { name: 'section_2', type: 'long', default: 0 },
      { name: 'section_3', type: 'long', default: 0 },
      { name: 'page', type: 'int' },
      { name: 'size', type: 'int' },
    ],
  });
  const cursor =
    'BHBzAMLrxocLALLN9OYUANTH8K8bAOid47cTAPqErvcDAKCWq5sQAKyUquwdAL7d8cYfAAIAyAE=';
  const buffer= Buffer.from(cursor, 'base64');
  const decode = schema.fromBuffer(buffer);
  const recovered: avroSchema = JSON.parse(decode.toString());
  return recovered;
}
```

I was told that golang uses UTF8 on the strings, while Javascript uses UTF-16, so I've attempt to convert the buffer into a utf-8 string and them run this string through the schema, but them I get another error:

```
[Nest] 102108   - 2021-02-26 18:54:56   [ExceptionsHandler] Unexpected token ♦ in JSON at position 0 +5897ms
SyntaxError: Unexpected token ♦ in JSON at position 0
    at JSON.parse (<anonymous>)
    at RecordType.Type.fromString (C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\avsc\lib\types.js:603:26)
    at Object.cursorDecodeAvsc (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\util\home.helper.js:59:27)    at HomeService.search (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.service.js:51:39)
    at HomeService.cardsGenerator (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.service.js:169:39)    at HomeService.homeFiltered (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.service.js:374:28)  
    at HomeController.FilteredCards (C:\Users\Rafael Morales\Documents\tom-bombadil\dist\home\home.v1.controller.js:30:39)
    at C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\@nestjs\core\router\router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Rafael Morales\Documents\tom-bombadil\node_modules\@nestjs\core\router\router-execution-context.js:46:28
```
using this code here:

```
function cursorDecodeAvsc(): avroSchema {
  const schema = Type.forSchema({
    namespace: 'cardstack.avro',
    type: 'record',
    name: 'Cursor',
    fields: [
      { name: 'type', type: 'string', default: 'ps' },
      { name: 'card_0', type: 'long', default: 0 },
      { name: 'card_1', type: 'long', default: 0 },
      { name: 'card_2', type: 'long', default: 0 },
      { name: 'card_3', type: 'long', default: 0 },
      { name: 'section_0', type: 'long', default: 0 },
      { name: 'section_1', type: 'long', default: 0 },
      { name: 'section_2', type: 'long', default: 0 },
      { name: 'section_3', type: 'long', default: 0 },
      { name: 'page', type: 'int' },
      { name: 'size', type: 'int' },
    ],
  });
  //console.log(`Original: ${cursor}`);
  const cursor =
    'BHBzAMLrxocLALLN9OYUANTH8K8bAOid47cTAPqErvcDAKCWq5sQAKyUquwdAL7d8cYfAAIAyAE=';
  const buffer= Buffer.from(cursor, 'base64');
  const decode = schema.fromString(buffer.toString('utf8'));
  console.log(decode);
  const recovered: avroSchema = JSON.parse(decode.toString());
  return recovered;
}
```
Do anyone have any idea on how can I solve this? 

The string `cursor` is value sent by the Golang client.

**Comment by mtth** [comment]
Hi @inm-rmorales. Trailing data errors indicate that there is leftover data in the buffer that you are decoding. You can use [`type.decode`](https://github.com/mtth/avsc/wiki/API#typedecodebuf-pos-resolver) to get more visibility:

```js
const b = Buffer.from(
  'BHBzAMLrxocLALLN9OYUANTH8K8bAOid47cTAPqErvcDAKCWq5sQAKyUquwdAL7d8cYfAAIAyAE=',
  'base64'
);

const t1 = avro.Type.forSchema({
  "namespace": "cardstack.avro",
  "type": "record",
  "name": "Cursor",
  "fields": [
    {"name":"type","type":"string", "default": "ps"},
    {"name":"card_0","type":"long", "default": 0},
    {"name":"card_1","type":"long", "default": 0},
    {"name":"card_2","type":"long", "default": 0},
    {"name":"card_3","type":"long", "default": 0},
    {"name":"section_0","type":"long", "default": 0},
    {"name":"section_1","type":"long", "default": 0},
    {"name":"section_2","type":"long", "default": 0},
    {"name":"section_3","type":"long", "default": 0},
    {"name":"page","type":"int"},
    {"name":"size","type":"int"}
  ]
});

const o = t1.decode(b);
console.log(o);
// {
//   value: Cursor {
//     type: 'ps',
//     card_0: 0,
//     card_1: 1484315361,
//     card_2: 0,
//     card_3: 2792264537,
//     section_0: 0,
//     section_1: 3674083818,
//     section_2: 0,
//     section_3: 2608621428,
//     page: 0,
//     size: 527810877
//   },
//   offset: 33
// }
console.log(b.slice(o.offset).toString('hex'));
// 00a096ab9b1000ac94aaec1d00beddf1c61f000200c801
```

From here we can notice a couple interesting things:

1. Though we only read 33 bytes out of the 56 in the buffer, decoding succeeded and the `type` field matches its default (`'ps'`). This is a good indication that base 64 decoding is good.
2. There are 23 bytes left in the buffer that do not belong to fields described in the schema. Usually this means that the schema is incomplete (e.g. is missing fields). In this case however, the pattern of decoded numeric values (0 followed by a non-0 value) hints at something else: each value is wrapped in a union. We can test this by tweaking the relevant fields:

```js
const t2 = avro.Type.forSchema({
  "namespace": "cardstack.avro",
  "type": "record",
  "name": "Cursor",
  "fields": [
    {"name":"type","type":"string", "default": "ps"},
    {"name":"card_0","type":["long", "null"], "default": 0}, // Union with arbitrary other type.
    {"name":"card_1","type":["long", "null"], "default": 0},
    {"name":"card_2","type":["long", "null"], "default": 0},
    {"name":"card_3","type":["long", "null"], "default": 0},
    {"name":"section_0","type":["long", "null"], "default": 0},
    {"name":"section_1","type":["long", "null"], "default": 0},
    {"name":"section_2","type":["long", "null"], "default": 0},
    {"name":"section_3","type":["long", "null"], "default": 0},
    {"name":"page","type":["int", "null"]},
    {"name":"size","type":["int", "null"]},
  ]
});

const c = t2.fromBuffer(b); // Succeeds (no trailing data).
console.log(c);
// Cursor {
//   type: 'ps',
//   card_0: 1484315361,
//   card_1: 2792264537,
//   card_2: 3674083818,
//   card_3: 2608621428,
//   section_0: 527810877,
//   section_1: 2176148880,
//   section_2: 4005905686,
//   section_3: 4235081567,
//   page: 1,
//   size: 100
// }
```

With this change the schema matches the buffer exactly: there is no more trailing data. The numbers also seem more natural than previously: the alternating zero/non-zero pattern is gone.

As a next step, I would recommend checking the code producing the data to confirm which schema is being used and/or if there is some automation which transforms schemas before encoding data.

**Comment by inm-rmorales** [comment]
I understand @mtth !!!
I will check with them, Thank you for your help!!
