### ISSUE TITLE
adding a field with a default value breaks the protocol

### ISSUE THREAD

**Issue by jfromaniello** [mtth/avsc#34]
Here is a rough test case:

```javascript
var avro = require('avsc');
var PassThrough = require('stream').PassThrough;
var pt1 = PassThrough();
var pt2 = PassThrough();
var writer_transport = {readable: pt1, writable: pt2};
var reader_transport = {readable: pt2, writable: pt1};


var protocol_definition = {
  types: [{
    type: 'record',
    name: 'Request',
    fields: [{
      type: 'string',
      name: 'name'
    }, {
      type: 'string',
      name: 'id'
    }]
  }, {
    type: 'record',
    name: 'Response',
    fields: [{
      type: 'string',
      name: 'result'
    }]
  }],
  messages: {
    test: {
      response: 'Response',
      request: [{
        type: 'Request',
        name: 'params'
      }]
    }
  },
  namespace: 'MyNamespace',
  protocol: 'MyProto'
};

var writer_protocol = avro.parse(protocol_definition);

writer_protocol.on('test', function(req, ee, cb) {
  console.log('got a request');
  cb(null, {
    result: 'OK'
  });
});

writer_protocol.createListener(writer_transport);


//change the Response message to include a new new_optional_field with default value to "123"
protocol_definition.types[1].fields.push({
  type: 'string',
  name: 'new_optional_field',
  'default': '123'
});

var reader_protocol = avro.parse(protocol_definition);

var ee = reader_protocol.createEmitter(reader_transport);
reader_protocol.emit('test', {
  params: {
    name: 'jose',
    id: '123'
  }
}, ee, function(err, res) {
  console.dir(arguments); // 9!
  process.exit(0);
});

```

It throws this error:

```
Error: no alias for test in MyNamespace.test
    at StatefulEmitter.MessageEmitter._finalizeHandshake (/Users/jose/Projects/auth0/auth0-vagrant/src/auth0-anomaly-detector/node_modules/avsc/lib/protocols.js:319:11)
    at MessageDecoder.onHandshakeData (/Users/jose/Projects/auth0/auth0-vagrant/src/auth0-anomaly-detector/node_modules/avsc/lib/protocols.js:548:23)
    at emitOne (events.js:77:13)
```

It works as expected if I remove the `namespace` field from the protocol.

**Comment by mtth** [comment]
Thanks for reporting this! `3.3.11` is out with the fix.

Running your test case, I now get:
```shell
$ node issue-34.js
got a request
{ '0': null,
  '1': Response { result: 'OK', new_optional_field: '123' } }
```

**Comment by jfromaniello** [comment]
Thank you for your awesome work!
