### ISSUE TITLE
[Bug] JSON Data buffer decoding parse error

### ISSUE THREAD

**Issue by dalisoft** [mtth/avsc#350]
# Bug Report

## Snippet

```js
const avro = require('avsc');

const type = avro.Type.forSchema({
  type: 'record',
  fields: [{ name: 'name', type: 'string' }]
});

const buff = Buffer.from(JSON.stringify({ name: 'John' })); // This maybe any JSON data with same schema as described, not Avro/avsc data
const from_str = type.fromBuffer(buff);

console.log('str', from_str);
```

## Excepted

Parse and get result of JSON parsed object

## Actual

```bash
❯ node avsc.js
/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-performance/node_modules/avsc/lib/types.js:594
    throw new Error('truncated buffer');
    ^

Error: truncated buffer
    at RecordType.Type.fromBuffer (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-performance/node_modules/avsc/lib/types.js:594:11)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-performance/avsc.js:12:23)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by mtth** [comment]
`fromBuffer` expects binary Avro-encoded input. You can use `fromString` to decode JSON input:

```js
const str = JSON.stringify({ name: 'John' });
const val = type.fromString(str);
```
