### ISSUE TITLE
[Bug] Nested `record` throws error 

### ISSUE THREAD

**Issue by dalisoft** [mtth/avsc#351]
# Bug

## Snippet
```js
const avsc = require('avsc');
const AvroCompile = avsc.Type.forSchema({
  type: 'record',
  fields: [
    { name: 'status', type: 'string' },
    {
      name: 'data',
      type: 'record',
      fields: [
        {
          name: 'user',
          type: 'record',
          fields: [
            { name: 'id', type: 'string' },
            { name: 'name', type: 'string' }
          ]
        }
      ]
    }
  ]
});
```

## Excepted

Working schema for converting input data to string

## Actual

```bash
    throw new Error(f('undefined type name: %s', schema));
    ^

Error: undefined type name: record
    at Function.Type.forSchema (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/node_modules/avsc/lib/types.js:174:11)
    at new Field (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/node_modules/avsc/lib/types.js:2798:20)
    at RecordType.<anonymous> (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/node_modules/avsc/lib/types.js:2119:17)
    at Array.map (<anonymous>)
    at new RecordType (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/node_modules/avsc/lib/types.js:2118:45)
    at /Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/node_modules/avsc/lib/types.js:223:14
    at Function.Type.forSchema (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/node_modules/avsc/lib/types.js:224:7)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Open_Source/nanoexpress/expirements/json-serialize/bench-serialize.js:32:31)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mtth** [comment]
This schema is invalid. Field types should be nested within the field object, no embedded:

```js
// Incorrect
fields: [ 
  {
    name: 'fieldName',
    type: 'record',
    fields: [ /* ... */ ],
    // ...
  }
]

// OK
fields: [ 
  {
    name: 'fieldName',
    type: {
      type: 'record',
      fields: [ /* ... */ ],
      // ...
    }
  }
]
```

Take a look at the spec for more examples: http://avro.apache.org/docs/current/spec.html#schema_record
