### ISSUE TITLE
Fixed type isn't recognized

### ISSUE THREAD

**Issue by valtonia** [mtth/avsc#372]
Hi.

Firstly, thanks for providing this awesome library!

My issue - given this schema (in **test.avsc**)
```
{
    "name": "test",
    "namespace": "some.name.space",
    "type": "record",
    "fields": [
        {
            "name": "id",
            "type": "int"
        },
        {
            "name": "name",
            "type": "fixed",
            "length": 25
        }
    ]
}
```

and this code (in **fail.js**)
```
import avro from 'avsc';
const registry = {};
avro.parse('./test.avsc', { registry });
console.log(registry);
```

I'm getting this error when I run **node fail.ts**
```
/avro/node_modules/avsc/lib/types.js:174
    throw new Error(f('undefined type name: %s', schema));
          ^

Error: undefined type name: some.name.space.fixed
    at Function.Type.forSchema (/avro/node_modules/avsc/lib/types.js:174:11)
    at new Field (/avro/node_modules/avsc/lib/types.js:2805:20)
    at RecordType.<anonymous> (/avro/node_modules/avsc/lib/types.js:2126:17)
    at Array.map (<anonymous>)
    at new RecordType (/avro/node_modules/avsc/lib/types.js:2125:45)
    at /avro/node_modules/avsc/lib/types.js:223:14
    at Function.Type.forSchema (/avro/node_modules/avsc/lib/types.js:224:7)
    at Object.parse (/avro/node_modules/avsc/lib/index.js:26:16)
    at file:///avro/build/fail.js:3:6
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
```

Node is version **14.17.4** and avsc library is version **5.7.3**

What am I doing wrong?

Thanks.

**Comment by mtth** [comment]
Hi @valtonia. You just need to nest the fixed type's definition further:

```
{
    "name": "test",
    "namespace": "some.name.space",
    "type": "record",
    "fields": [
        {
            "name": "id",
            "type": "int"
        },
        {
            "name": "name", // Name of the field
            "type": {"type": "fixed", "name": "MyFixedType", "size": 25} // Type definition
        }
    ]
}
```

Also note that `length` should be `size`.

**Comment by mtth** [comment]
Fixed types expect `Buffer` instances, not strings. You can use a logical type to do arbitrary validation on a string. Take a look [here](https://stackoverflow.com/a/37282006/1062617) for an example.

**Comment by valtonia** [comment]
Got it.  Thanks @mtth for your help.
