### ISSUE TITLE
fromBuffer failing on union ["null",  <custom record> ]

### ISSUE THREAD

**Issue by Axel92Dev** [mtth/avsc#376]
Hey Matthieu, thanks a lot for this awesome library!
We are using it "indirectly" as we are using Azure Schema Registry deserializer in a node Azure Function. The serialization part is done by a JAVA Microservice. 

I Hope Microsoft offer you a beer from time to time 🍺

The problem I am getting
```
 Exception: Error: invalid union index: -73904120
[2022-01-07T17:39:22.689Z] Stack: Error: invalid union index: -73904120
[2022-01-07T17:39:22.689Z]     at UnwrappedUnionType._read (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/avsc/lib/types.js:1318:11)
[2022-01-07T17:39:22.689Z]     at RecordType.readProviderCompanyAddress [as _read] (eval at RecordType._createReader (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/avsc/lib/types.js:2296:10), <anonymous>:11:8)
[2022-01-07T17:39:22.689Z]     at UnwrappedUnionType._read (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/avsc/lib/types.js:1316:23)
[2022-01-07T17:39:22.690Z]     at RecordType.readCompanyDataUpsert [as _read] (eval at RecordType._createReader (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/avsc/lib/types.js:2296:10), <anonymous>:10:8)
[2022-01-07T17:39:22.690Z]     at readValue (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/avsc/lib/types.js:2902:17)
[2022-01-07T17:39:22.690Z]     at RecordType.Type.fromBuffer (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/avsc/lib/types.js:599:13)
[2022-01-07T17:39:22.691Z]     at SchemaRegistryAvroSerializer.deserialize (/home/alromano/Projects/DataIngestion/aidexa-data-ingestion/node_modules/@azure/schema-registry-avro/dist/index.js:
```

I attached the Avro Schema (extension is `.txt` but it actually is a `.avsc`) and at the bottom of this post you can find the JSON message as it is deserialized by the Java Microservice, which is not failing.
[CompanyDataUpsertSchema.txt](https://github.com/mtth/avsc/files/7830501/CompanyDataUpsertSchema.txt)

As you can see it is failing in the **RecordType.readProviderCompanyAddress** part, and that field is a **union**
```
  {
            "name": "address",
            "type": [
                "null",
                {
                    "name": "ProviderCompanyAddress",
                    "type": "record",
                    "fields": [
```

I don't get if this problem is related to the ["int", "float"] unwrapping issue or if it is something else.
I can intervene in some way both on the Avro Schema and on the Java Microservice, but I'm struggling on what I should be doing.

Thanks a lot in advance, I hope you are able to give me some direction!

```json
{
	"vatNumber": "03281750129",
	"businessName": "RUSSO MATTEO",
	"fiscalCode": "RSSMTT92E12L682E",
	"cervedSubjectId": "361306459",
	"certifiedEmails": ["russomatteo.giardini@pec.it"],
	"websiteURL": null,
	"phoneNumber": null,
	"address": {
		"region": "Lombardia",
		"province": "VA",
		"municipality": "CARONNO VARESINO",
		"zipCode": "21040",
		"toponym": "VIA",
		"addressName": "FILIPPO TURATI",
		"addressNumber": "9",
		"latitude": 45.73831,
		"longitude": 8.83174,
		"istatMunicipalityCode": "012035",
		"istatGeographicZone": "Nord-ovest"
	},
	"userModifiedAddress": null,
	"activityStatusCode": "ATTIVA",
	"isOperative": true,
	"constitutionDate": "15-03-2012",
	"activityStartDate": "15-03-2012",
	"activityEndDate": null,
	"juridicalNature": "IMPRESA INDIVIDUALE",
	"reaCode": "VA 338183",
	"reaSubscriptionDate": "20-03-2012",
	"atecoCode": "813",
	"atecoDescription": "Cura e manutenzione del paesaggio (inclusi parchi, giardini e aiuole)",
	"atecoMacrosectorCode": null,
	"atecoMacrosectorDescription": null,
	"naceCode": "81.3",
	"naceDeclaration": "ATTIVITA' AMMINISTRATIVE E DI SERVIZI DI SUPPORTO",
	"naceDescription": "Attivita' di sistemazione del paesaggio",
	"naceDeclarationEnglish": "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
	"naceDescriptionEnglish": "Landscape service activities",
	"sicCodifications": [{
		"sicCode": "0782",
		"sicDeclarationEnglish": "Agriculture, Forestry, And Fishing",
		"sicDescriptionnEnglish": "Lawn and Garden Services"
	}],
	"raeCode": null,
	"raeDeclaration": null,
	"saeCode": null,
	"saeDeclaration": null,
	"noREAFormCode": null,
	"noREAFormDescription": null,
	"formCode": null,
	"formCodeDescription": null,
	"formClass": "DI",
	"employeesNumber": 1,
	"userModifiedEmployeesNumber": null,
	"officesNumber": null,
	"lastBalanceClosingDate": null,
	"billing": null,
	"userModifiedBilling": null,
	"shareCapital": 2000,
	"shareCapitalType": null,
	"grossProfit": null,
	"assets": null,
	"netWorth": null,
	"profitLoss": null,
	"referenceTimestamp": "2022-01-07T17:39:18Z"
}
```

**Comment by mtth** [comment]
Hey @Axel92Dev. Hard to say without seeing the serialization code or encoded output. The latter could contain a header for example. Can you share the hex-encoded buffer that produces the above error?

**Comment by Axel92Dev** [comment]
> Hey @Axel92Dev. Hard to say without seeing the serialization code or encoded output. The latter could contain a header for example. Can you share the hex-encoded buffer that produces the above error?

Here you have it :)
```
[0, 0, 0, 0, 97, 100, 57, 57, 99, 100, 98, 48, 102, 50, 98, 51, 52, 101, 101, 99, 98, 53, 56, 51, 100, 54, 56, 56, 101, 99, 51, 56, 97, 98, 48, 97, 22, 48, 51, 50, 56, 49, 55, 53, 48, 49, 50, 57, 2, 24, 82, 85, 83, 83, 79, 32, 77, 65, 84, 84, 69, 79, 2, 32, 82, 83, 83, 77, 84, 84, 57, 50, 69, 49, 50, 76, 54, 56, 50, 69, 2, 18, 51, 54, 49, 51, 48, 54, 52, 53, 57, 2, 2, 54, 114, 117, 115, 115, 111, 109, 97, 116, 116, 101, 111, 46, 103, 105, 97, 114, 100, 105, 110, 105, 64, 112, 101, 99, 46, 105, 116, 0, 0, 0, 2, 18, 76, 111, 109, 98, 97, 114, 100, 105, 97, 4, 86, 65, 32, 67, 65, 82, 79, 78, 78, 79, 32, 86, 65, 82, 69, 83, 73, 78, 79, 2, 10, 50, 49, 48, 52, 48, 2, 6, 86, 73, 65, 28, 70, 73, 76, 73, 80, 80, 79, 32, 84, 85, 82, 65, 84, 73, 2, 57, 2, -90, 39, 44, -15, -128, -34, 70, 64, 2, -46, -116, 69, -45, -39, -87, 33, 64, 2, 12, 48, 49, 50, 48, 51, 53, 2, 20, 78, 111, 114, 100, 45, 111, 118, 101, 115, 116, 0, 2, 12, 65, 84, 84, 73, 86, 65, 2, 1, 2, 20, 49, 53, 45, 48, 51, 45, 50, 48, 49, 50, 2, 20, 49, 53, 45, 48, 51, 45, 50, 48, 49, 50, 0, 2, 38, 73, 77, 80, 82, 69, 83, 65, 32, 73, 78, 68, 73, 86, 73, 68, 85, 65, 76, 69, 2, 18, 86, 65, 32, 51, 51, 56, 49, 56, 51, 2, 20, 50, 48, 45, 48, 51, 45, 50, 48, 49, 50, 2, 6, 56, 49, 51, 2, -118, 1, 67, 117, 114, 97, 32, 101, 32, 109, 97, 110, 117, 116, 101, 110, 122, 105, 111, 110, 101, 32, 100, 101, 108, 32, 112, 97, 101, 115, 97, 103, 103, 105, 111, 32, 40, 105, 110, 99, 108, 117, 115, 105, 32, 112, 97, 114, 99, 104, 105, 44, 32, 103, 105, 97, 114, 100, 105, 110, 105, 32, 101, 32, 97, 105, 117, 111, 108, 101, 41, 0, 0, 2, 8, 56, 49, 46, 51, 2, 98, 65, 84, 84, 73, 86, 73, 84, 65, 39, 32, 65, 77, 77, 73, 78, 73, 83, 84, 82, 65, 84, 73, 86, 69, 32, 69, 32, 68, 73, 32, 83, 69, 82, 86, 73, 90, 73, 32, 68, 73, 32, 83, 85, 80, 80, 79, 82, 84, 79, 2, 78, 65, 116, 116, 105, 118, 105, 116, 97, 39, 32, 100, 105, 32, 115, 105, 115, 116, 101, 109, 97, 122, 105, 111, 110, 101, 32, 100, 101, 108, 32, 112, 97, 101, 115, 97, 103, 103, 105, 111, 2, 90, 65, 68, 77, 73, 78, 73, 83, 84, 82, 65, 84, 73, 86, 69, 32, 65, 78, 68, 32, 83, 85, 80, 80, 79, 82, 84, 32, 83, 69, 82, 86, 73, 67, 69, 32, 65, 67, 84, 73, 86, 73, 84, 73, 69, 83, 2, 56, 76, 97, 110, 100, 115, 99, 97, 112, 101, 32, 115, 101, 114, 118, 105, 99, 101, 32, 97, 99, 116, 105, 118, 105, 116, 105, 101, 115, 2, 2, 2, 8, 48, 55, 56, 50, 2, 68, 65, 103, 114, 105, 99, 117, 108, 116, 117, 114, 101, 44, 32, 70, 111, 114, 101, 115, 116, 114, 121, 44, 32, 65, 110, 100, 32, 70, 105, 115, 104, 105, 110, 103, 2, 48, 76, 97, 119, 110, 32, 97, 110, 100, 32, 71, 97, 114, 100, 101, 110, 32, 83, 101, 114, 118, 105, 99, 101, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 68, 73, 2, 2, 0, 0, 0, 0, 0, 2, -96, 31, 0, 0, 0, 0, 0, 40, 50, 48, 50, 50, 45, 48, 49, 45, 48, 55, 84, 49, 55, 58, 51, 57, 58, 49, 56, 90]
```

**Comment by mtth** [comment]
There's a 36 byte prefix in the buffer. If you skip it, decoding works:

```js
const type = avro.Type.forSchema(/* schema above */);
const buf = Buffer.from(/* array above */);
console.log(type.fromBuffer(buf.slice(36))); // Works.
```

I recommend checking the encoding code to figure out why it gets added (and if you want to make use of it here).

**Comment by Axel92Dev** [comment]
> There's a 36 byte header in the buffer. If you skip it, decoding works:
> 
> ```js
> const type = avro.Type.forSchema(/* schema above */);
> const buf = Buffer.from(/* array above */);
> console.log(type.fromBuffer(buf.slice(36))); // Works.
> ```
> 
> I recommend checking the encoding code to figure out why it gets added (and if you want to make use of it here).

Thanks a lot for your help.
How you were able to troubleshoot it?

Because the same interaction happens on another AVRO Message (same Java producer, same Node receiver) and here serialization/deserialization works fine (the message is simpler in the structure).

I would like to understand if the 36 byte header is present in that message too.
Can you tell me what you did to troubleshoot?

Thanks

**Comment by Axel92Dev** [comment]
> There's a 36 byte header in the buffer. If you skip it, decoding works:
> 
> ```js
> const type = avro.Type.forSchema(/* schema above */);
> const buf = Buffer.from(/* array above */);
> console.log(type.fromBuffer(buf.slice(36))); // Works.
> ```
> 
> I recommend checking the encoding code to figure out why it gets added (and if you want to make use of it here).

I found out the 36 bytes header is something Azure Avro schema adds and remove when using its library.

But, now there is something stranger I am debugging the whole day with no luck, I hope you have a better intuition than mine :(

```javascript
const avro = require('avsc');

const type = avro.Type.forSchema({
    "name": "CompanyDataUpsert",
    "type": "record",
    "fields": [
        {
            "name": "vatNumber",
            "type": "string"
        },
        {
            "name": "businessName",
            "type": ["null", "string"],
            "doc": "Ragione Sociale"
        },
        {
            "name": "fiscalCode",
            "type": ["null", "string"],
            "doc": "Codice Fiscale dell'azienda"
        },
        {
            "name": "cervedSubjectId",
            "type": ["null", "string"],
            "doc": "Codice Soggetto Cerved dell'azienda"
        },
        {
            "name": "certifiedEmails",
            "type": [
                "null",
                {
                    "type": "array",
                    "items": "string"
                }
            ],
            "doc": "PEC aziendlai"
        },
        {
            "name": "websiteURL",
            "type": ["null", "string"],
            "doc": "Sito web aziendale"
        },
        {
            "name": "phoneNumber",
            "type": ["null", "string"],
            "doc": "Telefono fisso sede principale"
        },
        {
            "name": "address",
            "type": [
                "null",
                {
                    "name": "ProviderCompanyAddress",
                    "type": "record",
                    "fields": [
                        {
                            "name": "region",
                            "type": "string",
                            "doc": "Regione sede principale"
                        },
                        {
                            "name": "province",
                            "type": "string",
                            "doc": "Provincia sede principale"
                        },
                        {
                            "name": "municipality",
                            "type": "string",
                            "doc": "Comune sede principale"
                        },
                        {
                            "name": "zipCode",
                            "type": ["null", "string"],
                            "doc": "CAP sede principale"
                        },
                        {
                            "name": "toponym",
                            "type": ["null", "string"],
                            "doc": "Via/Viale/Piazza..."
                        },
                        {
                            "name": "addressName",
                            "type": "string",
                            "doc": "Nome della via/piazza sede principale"
                        },
                        {
                            "name": "addressNumber",
                            "type": "string",
                            "doc": "Numero Civico sede principale"
                        },
                        {
                            "name": "latitude",
                            "type": ["null", "double"],
                            "doc": "Latitudine sede principale"
                        },
                        {
                            "name": "longitude",
                            "type": ["null", "double"],
                            "doc": "Longitudine sede principale"
                        },
                        {
                            "name": "istatMunicipalityCode",
                            "type": ["null", "string"],
                            "doc": "Codice ISTAT Comune sede principale"
                        },
                        {
                            "name": "istatGeographicZone",
                            "type": ["null", "string"],
                            "doc": "Nome della via/piazza sede principale"
                        }
                    ]
                }
            ],
            "doc": "Indirizzo della sede principale dell'azienda"
        },
        {
            "name": "userModifiedAddress",
            "type": [
                "null",
                {
                    "name": "UserCompanyDataAddress",
                    "type": "record",
                    "fields": [
                        {
                            "name": "region",
                            "type": ["null", "string"],
                            "doc": "Regione sede principale"
                        },
                        {
                            "name": "province",
                            "type": ["null", "string"],
                            "doc": "Provincia sede principale"
                        },
                        {
                            "name": "municipality",
                            "type": ["null", "string"],
                            "doc": "Comune sede principale"
                        },
                        {
                            "name": "zipCode",
                            "type": ["null", "string"],
                            "doc": "CAP sede principale"
                        },
                        {
                            "name": "toponym",
                            "type": ["null", "string"],
                            "doc": "Via/Viale/Piazza..."
                        },
                        {
                            "name": "addressName",
                            "type": ["null", "string"],
                            "doc": "Nome della via/piazza sede principale"
                        },
                        {
                            "name": "addressNumber",
                            "type": ["null", "string"],
                            "doc": "Numero Civico sede principale"
                        },
                        {
                            "name": "latitude",
                            "type": ["null", "double"],
                            "doc": "Latitudine sede principale"
                        },
                        {
                            "name": "longitude",
                            "type": ["null", "double"],
                            "doc": "Longitudine sede principale"
                        },
                        {
                            "name": "istatMunicipalityCode",
                            "type": ["null", "string"],
                            "doc": "Codice ISTAT Comune sede principale"
                        },
                        {
                            "name": "istatGeographicZone",
                            "type": ["null", "string"],
                            "doc": "Nome della via/piazza sede principale"
                        }
                    ]
                }
            ],
            "doc": "Indirizzo della sede principale dell'azienda modificata dal cliente"
        },
        {
            "name": "activityStatusCode",
            "type": ["null", "string"],
            "doc": "A=attiva; C=cessata; D=inprocedure; F=fallita; G=amministrazione giudiziaria;I=inattiva; L=in scioglimento/liquidazione; N=in procedura concorsuale; P=iscrizione; R=registrata; S=sospesa; T=cancellata"
        },
        {
            "name": "isOperative",
            "type": ["null", "boolean"],
            "doc": "Flag sintetito che indica status operatività"
        },
        {
            "name": "constitutionDate",
            "type": ["null", "string"],
            "doc": "Data formale atto costitutivo (dd-MM-yyyy)"
        },
        {
            "name": "activityStartDate",
            "type": ["null", "string"],
            "doc": "Data inizio attività (dd-MM-yyyy)"
        },
        {
            "name": "activityEndDate",
            "type": ["null", "string"],
            "doc": "Data fine attività (dd-MM-yyyy)"
        },
        {
            "name": "juridicalNature",
            "type": ["null", "string"],
            "doc": "Natura giuridica"
        },
        {
            "name": "reaCode",
            "type": ["null", "string"],
            "doc": "Codice della Provincia della Camera di Commercio concatenato (tramite spazio singolo) al codice nel Repertorio Economico Amministrativo"
        },
        {
            "name": "reaSubscriptionDate",
            "type": ["null", "string"],
            "doc": "Data di iscrizione nel Repertorio Economico Amministrativo"
        },
        {
            "name": "atecoCode",
            "type": ["null", "string"],
            "doc": "Codice di classificazione dell'attività economica (Codice Ateco ISTAT 2007)"
        },
        {
            "name": "atecoDescription",
            "type": ["null", "string"],
            "doc": "Descrizione del Codice Ateco"
        },
        {
            "name": "atecoMacrosectorCode",
            "type": ["null", "string"],
            "doc": "Codice di classificazione del macrosettore"
        },
        {
            "name": "atecoMacrosectorDescription",
            "type": ["null", "string"],
            "doc": "Descrizione del macrosettore"
        },
        {
            "name": "naceCode",
            "type": ["null", "string"],
            "doc": "Codice di classificazione della nomenclatura delleAttività economiche"
        },
        {
            "name": "naceDeclaration",
            "type": ["null", "string"],
            "doc": "Declaratoria del Codice Nace"
        },
        {
            "name": "naceDescription",
            "type": ["null", "string"],
            "doc": "Descrizione del Codice Nace"
        },
        {
            "name": "naceDeclarationEnglish",
            "type": ["null", "string"],
            "doc": "Declaratoria del Codice Nace in lingua inglese"
        },
        {
            "name": "naceDescriptionEnglish",
            "type": ["null", "string"],
            "doc": "Descrizione del Codice Nace in lingua inglese"
        },
        {
            "name": "sicCodifications",
            "type": [
                "null",
                {
                    "type": "array",
                    "items": {
                        "name": "SicInfo",
                        "type": "record",
                        "fields": [
                            {
                                "name": "sicCode",
                                "type": ["null", "string"],
                                "doc": "Codice SIC"
                            },
                            {
                                "name": "sicDeclarationEnglish",
                                "type": ["null", "string"],
                                "doc": "Declaratoria SIC in inglese"
                            },
                            {
                                "name": "sicDescriptionnEnglish",
                                "type": ["null", "string"],
                                "doc": "Descrizione SIC in inglese"
                            }
                        ]
                    }
                }
            ],
            "doc": "Lista di codifiche SIC"
        },
        {
            "name": "raeCode",
            "type": ["null", "string"],
            "doc": "Codice di classificazione dei rami Attività economiche"
        },
        {
            "name": "raeDeclaration",
            "type": ["null", "string"],
            "doc": "Declaratoria del Codice Rae"
        },
        {
            "name": "saeCode",
            "type": ["null", "string"],
            "doc": "Codice di classificazione dei settori Attività economiche"
        },
        {
            "name": "saeDeclaration",
            "type": ["null", "string"],
            "doc": "Declaratoria del Codice Sae"
        },
        {
            "name": "noREAFormCode",
            "type": ["null", "string"],
            "doc": "Codice della forma del soggetto no REA"
        },
        {
            "name": "noREAFormDescription",
            "type": ["null", "string"],
            "doc": "Descrizione della forma del soggetto no REA"
        },
        {
            "name": "formCode",
            "type": ["null", "string"],
            "doc": "Codice della natura giuridica"
        },
        {
            "name": "formCodeDescription",
            "type": ["null", "string"],
            "doc": "Descirizone della natura giuridica"
        },
        {
            "name": "formClass",
            "type": ["null", "string"],
            "doc": "Codice della classe di natura giuridica del soggetto trovato. Il campo assume come valori possibili i seguenti (valori ammessi SC - Societa di Capitali, SP - Societa di Persone, DI - Ditta Individuale, AL - Altre forme giuridiche"
        },
        {
            "name": "employeesNumber",
            "type": ["null", "int"],
            "doc": "Numero dipendenti"
        },
        {
            "name": "userModifiedEmployeesNumber",
            "type": ["null", "int"],
            "doc": "Numero dipendenti inseriti dal cliente"
        },
        {
            "name": "officesNumber",
            "type": ["null", "int"],
            "doc": "Numero delle sedi dell'attività"
        },
        {
            "name": "lastBalanceClosingDate",
            "type": ["null", "string"],
            "doc": "Data di chiusura dell'ultimo bilancio dell'attività (dd-MM-yyyy)"
        },
        {
            "name": "billing",
            "type": ["null", "int"],
            "doc": "Fatturato in Euro dell'ultimo bilancio (da moltiplicare x 1000 in fase di Produzione messaggio se letto da Cerved)"
        },
        {
            "name": "userModifiedBilling",
            "type": ["null", "int"],
            "doc": "Fatturato in Euro dell'ultimo bilancio inserito dal cliente)"
        },
        {
            "name": "shareCapital",
            "type": ["null", "int"],
            "doc": "Capitale sociale in Euro dell'ultimo bilancio"
        },
        {
            "name": "shareCapitalType",
            "type": ["null", "string"],
            "doc": "Tipologia di Capitale sociale in Euro dell'ultimo bilancio"
        },
        {
            "name": "grossProfit",
            "type": ["null", "int"],
            "doc": "Margine Operativo Lordo dell'ultimo bilancio (da moltiplicare x 1000 in fase di Produzione messaggio se letto da Cerved)"
        },
        {
            "name": "assets",
            "type": ["null", "int"],
            "doc": "Attivo dello Stato Patrimoniale dell'ultimo bilancio (da moltiplicare x 1000 in fase di Produzione messaggio se letto da Cerved)"
        },
        {
            "name": "netWorth",
            "type": ["null", "int"],
            "doc": "Patrimonio netto dell'ultimo bilancio (da moltiplicare x 1000 in fase di Produzione messaggio se letto da Cerved)"
        },
        {
            "name": "profitLoss",
            "type": ["null", "int"],
            "doc": "Utile/perdita dell'esercizio (da moltiplicare x 1000 in fase di Produzione messaggio se letto da Cerved)"
        },
        {
            "name": "referenceTimestamp",
            "type": "string",
            "doc": "Il timestamp del momento in cui è avvenuto l'evento che ha scatentato il messaggio in formato UTC (yyyy-MM-ddThh:mm:ssZ) es: 2021-12-16T14:00:31Z"
        }
    ]
});

const arr2 = [0, 0, 0, 0, 56, 53, 57, 49, 52, 99, 48, 99, 55, 52, 52, 52, 52, 52, 57, 51, 98, 49, 100, 49, 50, 54, 53, 53, 53, 56, 101, 53, 100, 101, 57, 53, 22, 48, 51, 50, 56, 49, 55, 53, 48, 49, 50, 57, 2, 24, 82, 85, 83, 83, 79, 32, 77, 65, 84, 84, 69, 79, 2, 32, 82, 83, 83, 77, 84, 84, 57, 50, 69, 49, 50, 76, 54, 56, 50, 69, 2, 18, 51, 54, 49, 51, 48, 54, 52, 53, 57, 2, 2, 54, 114, 117, 115, 115, 111, 109, 97, 116, 116, 101, 111, 46, 103, 105, 97, 114, 100, 105, 110, 105, 64, 112, 101, 99, 46, 105, 116, 0, 0, 0, 2, 18, 76, 111, 109, 98, 97, 114, 100, 105, 97, 4, 86, 65, 32, 67, 65, 82, 79, 78, 78, 79, 32, 86, 65, 82, 69, 83, 73, 78, 79, 2, 10, 50, 49, 48, 52, 48, 2, 6, 86, 73, 65, 28, 70, 73, 76, 73, 80, 80, 79, 32, 84, 85, 82, 65, 84, 73, 2, 57, 2, -90, 39, 44, -15, -128, -34, 70, 64, 2, -46, -116, 69, -45, -39, -87, 33, 64, 2, 12, 48, 49, 50, 48, 51, 53, 2, 20, 78, 111, 114, 100, 45, 111, 118, 101, 115, 116, 0, 2, 12, 65, 84, 84, 73, 86, 65, 2, 1, 2, 20, 49, 53, 45, 48, 51, 45, 50, 48, 49, 50, 2, 20, 49, 53, 45, 48, 51, 45, 50, 48, 49, 50, 0, 2, 38, 73, 77, 80, 82, 69, 83, 65, 32, 73, 78, 68, 73, 86, 73, 68, 85, 65, 76, 69, 2, 18, 86, 65, 32, 51, 51, 56, 49, 56, 51, 2, 20, 50, 48, 45, 48, 51, 45, 50, 48, 49, 50, 2, 6, 56, 49, 51, 2, -118, 1, 67, 117, 114, 97, 32, 101, 32, 109, 97, 110, 117, 116, 101, 110, 122, 105, 111, 110, 101, 32, 100, 101, 108, 32, 112, 97, 101, 115, 97, 103, 103, 105, 111, 32, 40, 105, 110, 99, 108, 117, 115, 105, 32, 112, 97, 114, 99, 104, 105, 44, 32, 103, 105, 97, 114, 100, 105, 110, 105, 32, 101, 32, 97, 105, 117, 111, 108, 101, 41, 0, 0, 2, 8, 56, 49, 46, 51, 2, 98, 65, 84, 84, 73, 86, 73, 84, 65, 39, 32, 65, 77, 77, 73, 78, 73, 83, 84, 82, 65, 84, 73, 86, 69, 32, 69, 32, 68, 73, 32, 83, 69, 82, 86, 73, 90, 73, 32, 68, 73, 32, 83, 85, 80, 80, 79, 82, 84, 79, 2, 78, 65, 116, 116, 105, 118, 105, 116, 97, 39, 32, 100, 105, 32, 115, 105, 115, 116, 101, 109, 97, 122, 105, 111, 110, 101, 32, 100, 101, 108, 32, 112, 97, 101, 115, 97, 103, 103, 105, 111, 2, 90, 65, 68, 77, 73, 78, 73, 83, 84, 82, 65, 84, 73, 86, 69, 32, 65, 78, 68, 32, 83, 85, 80, 80, 79, 82, 84, 32, 83, 69, 82, 86, 73, 67, 69, 32, 65, 67, 84, 73, 86, 73, 84, 73, 69, 83, 2, 56, 76, 97, 110, 100, 115, 99, 97, 112, 101, 32, 115, 101, 114, 118, 105, 99, 101, 32, 97, 99, 116, 105, 118, 105, 116, 105, 101, 115, 2, 2, 2, 8, 48, 55, 56, 50, 2, 68, 65, 103, 114, 105, 99, 117, 108, 116, 117, 114, 101, 44, 32, 70, 111, 114, 101, 115, 116, 114, 121, 44, 32, 65, 110, 100, 32, 70, 105, 115, 104, 105, 110, 103, 2, 48, 76, 97, 119, 110, 32, 97, 110, 100, 32, 71, 97, 114, 100, 101, 110, 32, 83, 101, 114, 118, 105, 99, 101, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 68, 73, 2, 2, 0, 0, 0, 0, 0, 2, -96, 31, 0, 0, 0, 0, 0, 40, 50, 48, 50, 50, 45, 48, 49, 45, 49, 48, 84, 49, 55, 58, 48, 50, 58, 49, 54, 90]
const arr3 = [0, 0, 0, 0, 56, 53, 57, 49, 52, 99, 48, 99, 55, 52, 52, 52, 52, 52, 57, 51, 98, 49, 100, 49, 50, 54, 53, 53, 53, 56, 101, 53, 100, 101, 57, 53, 22, 48, 51, 50, 56, 49, 55, 53, 48, 49, 50, 57, 2, 24, 82, 85, 83, 83, 79, 32, 77, 65, 84, 84, 69, 79, 2, 32, 82, 83, 83, 77, 84, 84, 57, 50, 69, 49, 50, 76, 54, 56, 50, 69, 2, 18, 51, 54, 49, 51, 48, 54, 52, 53, 57, 2, 2, 54, 114, 117, 115, 115, 111, 109, 97, 116, 116, 101, 111, 46, 103, 105, 97, 114, 100, 105, 110, 105, 64, 112, 101, 99, 46, 105, 116, 0, 0, 0, 2, 18, 76, 111, 109, 98, 97, 114, 100, 105, 97, 4, 86, 65, 32, 67, 65, 82, 79, 78, 78, 79, 32, 86, 65, 82, 69, 83, 73, 78, 79, 2, 10, 50, 49, 48, 52, 48, 2, 6, 86, 73, 65, 28, 70, 73, 76, 73, 80, 80, 79, 32, 84, 85, 82, 65, 84, 73, 2, 57, 2, 239, 191, 189, 39, 44, 239, 191, 189, 239, 191, 189, 70, 64, 2, 210, 140, 69, 239, 191, 189, 217, 169, 33, 64, 2, 12, 48, 49, 50, 48, 51, 53, 2, 20, 78, 111, 114, 100, 45, 111, 118, 101, 115, 116, 0, 2, 12, 65, 84, 84, 73, 86, 65, 2, 1, 2, 20, 49, 53, 45, 48, 51, 45, 50, 48, 49, 50, 2, 20, 49, 53, 45, 48, 51, 45, 50, 48, 49, 50, 0, 2, 38, 73, 77, 80, 82, 69, 83, 65, 32, 73, 78, 68, 73, 86, 73, 68, 85, 65, 76, 69, 2, 18, 86, 65, 32, 51, 51, 56, 49, 56, 51, 2, 20, 50, 48, 45, 48, 51, 45, 50, 48, 49, 50, 2, 6, 56, 49, 51, 2, 239, 191, 189, 1, 67, 117, 114, 97, 32, 101, 32, 109, 97, 110, 117, 116, 101, 110, 122, 105, 111, 110, 101, 32, 100, 101, 108, 32, 112, 97, 101, 115, 97, 103, 103, 105, 111, 32, 40, 105, 110, 99, 108, 117, 115, 105, 32, 112, 97, 114, 99, 104, 105, 44, 32, 103, 105, 97, 114, 100, 105, 110, 105, 32, 101, 32, 97, 105, 117, 111, 108, 101, 41, 0, 0, 2, 8, 56, 49, 46, 51, 2, 98, 65, 84, 84, 73, 86, 73, 84, 65, 39, 32, 65, 77, 77, 73, 78, 73, 83, 84, 82, 65, 84, 73, 86, 69, 32, 69, 32, 68, 73, 32, 83, 69, 82, 86, 73, 90, 73, 32, 68, 73, 32, 83, 85, 80, 80, 79, 82, 84, 79, 2, 78, 65, 116, 116, 105, 118, 105, 116, 97, 39, 32, 100, 105, 32, 115, 105, 115, 116, 101, 109, 97, 122, 105, 111, 110, 101, 32, 100, 101, 108, 32, 112, 97, 101, 115, 97, 103, 103, 105, 111, 2, 90, 65, 68, 77, 73, 78, 73, 83, 84, 82, 65, 84, 73, 86, 69, 32, 65, 78, 68, 32, 83, 85, 80, 80, 79, 82, 84, 32, 83, 69, 82, 86, 73, 67, 69, 32, 65, 67, 84, 73, 86, 73, 84, 73, 69, 83, 2, 56, 76, 97, 110, 100, 115, 99, 97, 112, 101, 32, 115, 101, 114, 118, 105, 99, 101, 32, 97, 99, 116, 105, 118, 105, 116, 105, 101, 115, 2, 2, 2, 8, 48, 55, 56, 50, 2, 68, 65, 103, 114, 105, 99, 117, 108, 116, 117, 114, 101, 44, 32, 70, 111, 114, 101, 115, 116, 114, 121, 44, 32, 65, 110, 100, 32, 70, 105, 115, 104, 105, 110, 103, 2, 48, 76, 97, 119, 110, 32, 97, 110, 100, 32, 71, 97, 114, 100, 101, 110, 32, 83, 101, 114, 118, 105, 99, 101, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 68, 73, 2, 2, 0, 0, 0, 0, 0, 2, 239, 191, 189, 31, 0, 0, 0, 0, 0, 40, 50, 48, 50, 50, 45, 48, 49, 45, 49, 48, 84, 49, 55, 58, 48, 57, 58, 49, 48, 90]

const buf2 = Buffer.from(arr2);
const buf3 = Buffer.from(arr3);




console.log(type.fromBuffer(buf2.slice(36))); // Works.
console.log(type.fromBuffer(buf3.slice(36))); // Works.
```

**arr2** is the byte array i pick from the Java microservice Log.
**arr3** is the byte array passed to my Azure Function which is invoked everytime a new message arrives on a subscription of the service bus.

arr3 fails to parse with the `"Error: invalid union index: -73904120"` while the first works, as per your suggestion.

I don't really understand what happens near the double values... :(

**Comment by mtth** [comment]
One thing that stands out is that `arr2`'s buffer input array contains negative values which might not be handled well everywhere, maybe something to look into. The logic which produces these buffers is outside of `avsc` and I'm not familiar with it so I'm afraid I can't provide much more help beyond that unfortunately.

**Comment by Axel92Dev** [comment]
> One thing that stands out is that `arr2`'s buffer input array contains negative values which might not be handled well everywhere, maybe something to look into. The logic which produces these buffers is outside of `avsc` and I'm not familiar with it so I'm afraid I can't provide much more help beyond that unfortunately.

Thanks a lot for your suggestion, you truly are a nice person :)

**Comment by Axel92Dev** [comment]
If anyone googled and found this post, it was just a missing setting not documented by Microsoft...

You have to put it in your binding `function.json`

```diff
{
  "bindings": [
    {
      "name": "mySbMsg",
      "type": "serviceBusTrigger",
+     "dataType": "binary",
      "direction": "in",
      "topicName": "%TOPIC_NAME%",
      "subscriptionName": "%ONBOARDING_DATA_SUBSCRIPTION_NAME%",
      "connection": "SERVICEBUS_CONNECTION_STRING"
    }
  ],
  "scriptFile": "../dist/OnboardingDataTrigger/index.js"
}
```
