### ISSUE TITLE
JSON data for Avro decimal

### ISSUE THREAD

**Issue by benjamin-mogensen** [mtth/avsc#391]
Hi, this is more of a question than an issue. Having a very simple schema like this:
```
{
  "name": "TestValue",
  "type": "record",
  "fields": [
    {
      "name": "Value",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 29,
        "scale": 14
      }
    }
  ]
}
```

JSON data:
```
{
  "Value": 100.0
}
```

I am using an error hook for validation that looks like defined [here](https://github.com/mtth/avsc/issues/148) and I get this error:
```
not a valid "bytes": 100
```

- How do I correctly represent a `Value` in a JSON sample that has to validate against the above schema using Avsc?

**Comment by mtth** [comment]
By default, `bytes` types expect `Buffer` instances as values. You'll need to register a logical type following the instructions [here](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) to allow other representations. The doc includes a `DecimalType` example that you could use as starting point for your use-case.

**Comment by benjamin-mogensen** [comment]
@mtth thanks a lot for your answer and to pointing me to the logical type documentation. I have tried this but I simply cannot get it to work properly. It may be that I do not understand how to properly `require` those classes to use them with the Avro logical types. Below is my tests:

**Date:**
I have copy pasted the content of the `date.js` to a file under my `src` folder called `DateType.js`.
```javascript
const avro = require('avsc')
const { DateType } = require('../src/DateType.js')
const schema = {
  name: 'Transaction',
  type: 'record',
  fields: [
    {name: 'time', type: {type: 'long', logicalType: 'timestamp-millis'}}
  ]
}
const type = avro.Type.forSchema(
  schema,
  {logicalTypes: {'timestamp-millis': DateType}}
)
const transaction = {
  time: new Date('Thu Nov 05 2015 11:38:05 GMT-0800 (PST)')
}
const buf = type.toBuffer(transaction);
const date = type.fromBuffer(buf).time
```

Above gives me this error:
```console
 Error: invalid "long": "2015-11-05T19:38:05.000Z"
  at throwInvalidError (node_modules/avsc/lib/types.js:3028:9)
  at LongType._write (node_modules/avsc/lib/types.js:925:5)
  at RecordType.writeTransaction [as _write] (eval at RecordType._createWriter (node_modules/avsc/lib/types.js:2341:10), <anonymous>:4:6)
  at RecordType.Type.toBuffer (node_modules/avsc/lib/types.js:656:8)
  at Context.<anonymous> (tests/TestAvroSampleDataValidator.js:57:22)
  at processImmediate (node:internal/timers:466:21)
```

**Decimal:**
I have copy pasted the content of the `decimal.js` to a file under my `src` folder called `DecimalType.js`.
```javascript
const avro = require('avsc')
const { DecimalType } = require('../src/DecimalType.js')
const schema = {
  name: 'Transaction',
  type: 'record',
  fields: [
    {name: 'amount', type: {type: 'bytes', logicalType: 'decimal', precision: 29, scale: 14}}
  ]
}
const type = avro.Type.forSchema(
  schema,
  {logicalTypes: {'decimal': DecimalType}}
)
const transaction = {
  amount: 100.5
}
const buf = type.toBuffer(transaction);
const decimal = type.fromBuffer(buf).amount
})
```

Above gives me this error:
```console
 Error: invalid "bytes": 100.5
  at throwInvalidError (node_modules/avsc/lib/types.js:3028:9)
  at BytesType._write (node_modules/avsc/lib/types.js:1130:5)
  at RecordType.writeTransaction [as _write] (eval at RecordType._createWriter (node_modules/avsc/lib/types.js:2341:10), <anonymous>:4:6)
  at RecordType.Type.toBuffer (node_modules/avsc/lib/types.js:656:8)
  at Context.<anonymous> (tests/TestAvroSampleDataValidator.js:80:22)
  at processImmediate (node:internal/timers:466:21)
```

I am sure it's just me doing something wrong, but I simply cannot spot it.

**Comment by benjamin-mogensen** [comment]
I ended up modifying the logical type somewhat to get it working for me. Pasting below (rather long code) to show how I made it work for my use case where the JSON data has to validate against our Avro schemas.

**Date logical type**
```javascript
'use strict'
const avro = require('avsc')
class AvroDateType extends avro.types.LogicalType {
  _fromValue (val) {
    return new Date(val)
  }
  _toValue (date) {
    if (date instanceof Date) {
      return date
    } else if (date instanceof String || typeof date === 'string') {
      try {
        return Date.parse(date)
      } catch (error) {
        return undefined
      }
    } else {
      return undefined
    }
  }
  _resolve (type) {
    if (avro.Type.isType(type, 'long', 'string', 'logical:timestamp-millis')) {
      return this._fromValue
    }
  }
}
module.exports = {
  AvroDateType
}
```

**Decimal logical type**
```javascript
'use strict'

const avro = require('avsc')
const util = require('util')

function DecimalType (attrs, opts) {
  avro.types.LogicalType.call(this, attrs, opts)
  const precision = attrs.precision
  if (precision !== (precision | 0) || precision <= 0) {
    throw new Error('invalid precision')
  }
  const scale = attrs.scale
  if (scale !== (scale | 0) || scale < 0 || scale > precision) {
    throw new Error('invalid scale')
  }
  const type = this.underlyingType
  if (avro.Type.isType(type, 'fixed')) {
    const size = type.size
    const maxPrecision = Math.log(Math.pow(2, 8 * size - 1) - 1) / Math.log(10)
    if (precision > (maxPrecision | 0)) {
      throw new Error('fixed size too small to hold required precision')
    }
  }
  this.Decimal = Decimal
  function Decimal (unscaled) { this.unscaled = unscaled }
  Decimal.prototype.precision = precision
  Decimal.prototype.scale = scale
  Decimal.prototype.toNumber = function () {
    return this.unscaled * Math.pow(10, -scale)
  }
}
util.inherits(DecimalType, avro.types.LogicalType)

DecimalType.prototype._fromValue = function (val) {
  const unscaled = val.readIntBE(0, val.length)
  return new this.Decimal(unscaled)
}

DecimalType.prototype._toValue = function (dec) {
  if (dec instanceof this.Decimal || typeof dec === 'number') {
    // TODO number is not being handled correctly here
    const type = this.underlyingType
    const unscaled = dec.unscaled
    let buf
    if (avro.Type.isType(type, 'fixed')) {
      buf = Buffer.alloc(type.size)
    } else {
      const size = Math.log(unscaled > 0 ? unscaled : -2 * unscaled) / (Math.log(2) * 8) | 0
      buf = Buffer.alloc(size + 1)
    }
    buf.writeIntBE(unscaled, 0, buf.length)
    return buf
  } else {
    throw new Error('invalid decimal')
  }
}

DecimalType.prototype._resolve = function (type) {
  if (
    avro.Type.isType(type, 'logical:decimal') &&
    type.Decimal.prototype.precision === this.Decimal.prototype.precision &&
    type.Decimal.prototype.scale === this.Decimal.prototype.scale
  ) {
    return function (dec) { return dec }
  }
}

DecimalType.prototype._export = function (attrs) {
  attrs.precision = this.Decimal.prototype.precision
  attrs.scale = this.Decimal.prototype.scale
}

module.exports = {
  DecimalType
}
```

Then in my sample data validator implementation I require them like this:

```javascript
const { AvroDateType } = require('./AvroDateType.js')
const { DecimalType } = require('./AvroDecimalType.js')
```

And use them like this:

```javascript
// Read  and parse the Avro schema
let avroSchema = null
try {
  const schemaObject = JSON.parse(fs.readFileSync(schemaFile))
  avroSchema = avro.Type.forSchema(schemaObject,
    { logicalTypes: { 'timestamp-millis': AvroDateType, decimal: DecimalType } }
  )
} catch (error) {
   // ... some handling
}
```

This works fine for what we need at least. Being able to have dates and decimals in some JSON instance data and then have that validate against the Avro having those logical types. However there are some funky stuff with the decimal `_toValue` that I don't quite understand, but for now I will leave that. What we really need is to have Avro schema, some sample data and then after design give that "package" to event consumer.
