### ISSUE TITLE
Record object with `fixed` field throws error

### ISSUE THREAD

**Issue by edulop91** [mtth/avsc#50]
Hello,

I recently ran into an error and was wondering if this was expected behavior. 
```js
var schema = {
  type: 'record',
  name: 'something',
  fields: [
    { name: 'payload', type: 'fixed', size: 10 }
  ]
};

avsc.parse(schema)
```
Fails with: 
```
'Error: undefined type name: fixed',
at createType (node_modules/avsc/lib/types.js:92:11)',
     '    at new Field (node_modules/avsc/lib/types.js:2371:16)',
     '    at RecordType.<anonymous> (node_modules/avsc/lib/types.js:1816:17)',
 '    at Array.map (native)',
     '    at new RecordType (node_modules/avsc/lib/types.js:1815:31)',
     '    at node_modules/avsc/lib/types.js:135:14',
     '    at Object.createType (node_modules/avsc/lib/types.js:136:7)',
     '    at Object.parse (node_modules/avsc/lib/index.js:31:11)'
```

node v4.42, avsc 4.1.0

**Comment by mtth** [comment]
Avro notation is a bit tricky, field types are nested under the the field's `type` field. You can take a look at [the record spec](https://avro.apache.org/docs/current/spec.html#schema_record) for the full description.

In your case, editing the schema as follows should do the trick (you were close!):

```javascript
var schema = {
  type: 'record',
  name: 'something',
  fields: [
    {
      name: 'payload', // This is the field's name.
      type: {name: 'Payload', type: 'fixed', size: 10} // The field's type
    }
  ]
};
```
