### ISSUE TITLE
ArrayBuffer to Buffer not working

### ISSUE THREAD

**Issue by miguelmota** [mtth/avsc#58]
```javascript
const avro = require('avsc');

const type = avro.parse({
  name: 'Pet',
  type: 'record',
  fields: [
    {name: 'kind', type: {name: 'Kind', type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'},
  ]
});

const buf = type.toBuffer({
  kind: 'CAT',
  name: 'Bob'
});

const arrayBuffer = buf.buffer;
const newBuf = new Buffer(arrayBuffer);

const val = type.fromBuffer(newBuf);

console.log(val);
```

output

```bash
/Users/mota/Sandbox/avro-demo/node_modules/avsc/lib/types.js:1337
    throw new Error(f('invalid %s enum index: %s', this._name, index));
    ^

Error: invalid Kind enum index: -50
    at EnumType._read (/Users/mota/Sandbox/avro-demo/node_modules/avsc/lib/types.js:1337:11)
    at RecordType.readPet [as _read] (eval at <anonymous> (/Users/mota/Sandbox/avro-demo/node_modules/avsc/lib/types.js:1957:10), <anonymous>:5:8)
    at readValue (/Users/mota/Sandbox/avro-demo/node_modules/avsc/lib/types.js:2471:17)
    at RecordType.Type.fromBuffer (/Users/mota/Sandbox/avro-demo/node_modules/avsc/lib/types.js:305:13)
    at Object.<anonymous> (/Users/mota/Sandbox/avro-demo/index.js:20:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by mtth** [comment]
`newBuf` isn't what you think it is:
```javascript
// ...
const buf = type.toBuffer({
  kind: 'CAT',
  name: 'Bob'
});
console.log(buf.length); // 5
const newBuf = new Buffer(buf.buffer);
console.log(newBuf.length); // 8192
```

`buf.buffer` returns `buf`'s backing `ArrayBuffer` which typically contains more data than just `buf`'s. You need to specify both an offset and a length when constructing `newBuf`:

```javascript
const newBuf = new Buffer(buf.buffer, buf.offset, buf.length);
```
(On recent versions of node, you might consider using [`Buffer.from`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_arraybuffer_byteoffset_length).)

**Comment by miguelmota** [comment]
@mtth thanks for the clarification!
