### ISSUE TITLE
Fails hard on complex schema

### ISSUE THREAD

**Issue by shellscape** [mtth/avsc#60]
Give the following schema:

```json
{
  "namespace": "com.gilt.gumshoe.v1",
  "type": "record",
  "name": "GumshoeEvent",
  "fields": [
    {"name": "uuid", "type": "string"},

    {"name": "eventName", "type": "string"},
    {"name": "eventData", "type": ["null", "string"], "default": null},

    {"name": "gumshoe", "type": ["null", "string"], "default": null, "doc": "The version of the CDN/gumshoe.js script, for debugging purposes. "},

    {"name": "sessionUuid", "type": "string"},

    {"name": "timestamp", "type": "long"},
    {"name": "timezoneOffset", "type": "long"},

    {"name": "giltData", "type":
      {"type": "record",
       "name": "GiltData",
       "namespace": "com.gilt.gumshoe.v1.GumshoeEvent.GiltData",
       "fields": [
          {"name": "abTests", "type": ["null", "string"], "default": null},
          {"name": "applicationName", "type": ["null", "string"], "default": null},
          {"name": "channel", "type": ["null", "string"], "default": null},
          {"name": "groups", "type": ["null", "string"], "default": null},
          {"name": "guid", "type": ["null", "string"], "default": null},
          {"name": "hasPurchased", "type": ["null", "boolean"], "default": null},
          {"name": "isBotRequest", "type": ["null", "boolean"], "default": null},
          {"name": "isLoyaltyUser", "type": ["null", "boolean"], "default": null},
          {"name": "loyaltyStatus", "type": ["null", "string"], "default": null},
          {"name": "mode", "type": ["null", "string"], "default": null},
          {"name": "pricer", "type": ["null", "string"], "default": null},
          {"name": "section", "type": ["null", "string"], "default": null},
          {"name": "store", "type": ["null", "string"], "default": null},
          {"name": "subsite", "type": ["null", "string"], "default": null},
          {"name": "timezone", "type": ["null", "string"], "default": null},
          {"name": "vendorUserId", "type": ["null", "string"], "default": null},

          {"name": "tracking_api", "type": [
              "null",
              {"type": "record",
               "name": "TrackingAPI",
               "namespace": "com.gilt.gumshoe.v1.GumshoeEvent.GiltData.TrackingAPI",
               "doc": "The version of the tracking_api.gumshoe module, for debugging purposes.",
               "fields": [
                  {"name": "gumshoe", "type": ["null", "string"], "default": null}              ]
              }
            ],
            "default": null
          }
        ]
      }
    },

    {"name": "pageData", "type":
      {
        "type": "record",
        "name": "PageData",
        "namespace": "com.gilt.gumshoe.v1.GumshoeEvent.PageData",
        "fields": [
          {"name": "characterSet", "type": "string"},
          {"name": "colorDepth", "type": "string"},
          {"name": "cookie", "type": ["null", "string"], "default": null},
          {"name": "googleClickId", "type": "string"},
          {"name": "hash", "type": "string"},
          {"name": "host", "type": "string"},
          {"name": "hostName", "type": "string"},
          {"name": "ipAddress", "type": "string"},
          {"name": "javaEnabled", "type": "boolean"},
          {"name": "language", "type": "string"},
          {"name": "loginKey", "type": "string"},
          {"name": "origin", "type": "string"},
          {"name": "path", "type": "string"},
          {"name": "platform", "type": "string"},
          {"name": "plugins", "type": ["null", "string"], "default": null},
          {"name": "port", "type": "int"},
          {"name": "promotionKey", "type": "string"},
          {"name": "protocol", "type": "string"},
          {"name": "queryString", "type": "string"},
          {"name": "referer", "type": "string"},
          {"name": "screenAvailHeight", "type": "int"},
          {"name": "screenAvailWidth", "type": "int"},
          {"name": "screenHeight", "type": "int"},
          {"name": "screenOrientationAngle", "type": "int"},
          {"name": "screenOrientationType", "type": "string"},
          {"name": "screenPixelDepth", "type": "string"},
          {"name": "screenResolution", "type": "string"},
          {"name": "screenWidth", "type": "int"},
          {"name": "title", "type": "string"},
          {"name": "url", "type": "string"},
          {"name": "userAgent", "type": "string"},
          {"name": "utmCampaign", "type": "string"},
          {"name": "utmContent", "type": "string"},
          {"name": "utmMedium", "type": "string"},
          {"name": "utmSource", "type": "string"},
          {"name": "utmTerm", "type": "string"},
          {"name": "viewportHeight", "type": "int"},
          {"name": "viewportResolution", "type": "string"},
          {"name": "viewportWidth", "type": "int"}
        ]
      }
    }
  ]
}
```

The following error is reported:

```
/.../node_modules/avsc/lib/utils.js:522
  return this.buf.utf8Slice(pos, pos + len);
                  ^

RangeError: out of range index
    at RangeError (native)
    at Tap.readString (/.../node_modules/avsc/lib/utils.js:522:19)
    at StringType._read (/.../node_modules/avsc/lib/types.js:736:58)
    at RecordType.readGumshoeEvent [as _read] (eval at <anonymous> (/.../node_modules/avsc/lib/types.js:1957:10), <anonymous>:5:8)
    at readValue (/.../node_modules/avsc/lib/types.js:2471:17)
    at RecordType.Type.fromBuffer (/.../node_modules/avsc/lib/types.js:305:13)
```

If I had to venture a guess, this lib is suffering from the same lack of support that node-avro-io has for union types. But that's just a wild stab in the dark.

**Comment by shellscape** [comment]
Figured out what the issue was with this one: The "uuid" field was expected to be a buffer, rather than a string. Some automagical conversion internally would be immensely useful.

**Comment by mtth** [comment]
Your `uuid` field is defined as a `string` type above, If you'd like the `uuid` field to be a `Buffer` you can use the `bytes` or `fixed` instead.

> Some automagical conversion internally would be immensely useful.

You can use [logical types](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) for this (e.g. implementing a type which can read both strings and `Buffer` objects). Or even just [schema evolution](https://github.com/mtth/avsc/wiki/Advanced-usage#schema-evolution) (since `string` and `bytes` types are compatible).

**Comment by mtth** [comment]
@shellscape - I would appreciate if you could edit your comment [in this related issue](https://github.com/jamesbrucepower/node-avro-io/issues/28#issuecomment-235266534) since your initial suspicion was false.
