### ISSUE TITLE
any way to convert a Type instance into the raw message

### ISSUE THREAD

**Issue by cludden** [mtth/avsc#77]
if i have
```javascript
const person = {
  id: 1,
  first: 'bob',
  last: 'smith'
}
```

and serialize it
```javascript
const encoded = Person.toBuffer(person)
const decoded = Person.fromBuffer(encoded)
assert.deepEqual(decoded, person) // yields false
```

wondering if there is a way to get the underlying message
```javascript
// something like
decoded.toObject()
// or
decoded.getRaw()
```

**Comment by mtth** [comment]
That's odd, it works fine when I try it (see snippet below). Which `assert` module are you using? Are you running the code via `node` or in a browser (if so, which one)?

```javascript
const avro = require('avsc');
const assert = require('assert');

const type = avro.parse({
  name: 'Person',
  type: 'record',
  fields: [
    {name: 'id', type: 'int'},
    {name: 'first', type: 'string'},
    {name: 'last', type: 'string'}
  ]
});

const personBefore = {id: 1, first: 'bob', last: 'smith'};
const buf = type.toBuffer(personBefore);
const personAfter = type.fromBuffer(buf);

assert.deepEqual(personAfter, personBefore); // Ok.
```

**Comment by cludden** [comment]
hmmm.. apparently theres an issue with `chai` then
```javascript
'use strict'

const assert = require('assert')
const avro = require('avsc')
const { assert: chaiAssert } = require('chai')
const { describe, it } = require('mocha')

describe('avsc', function () {
  it('encoded/decoded should deep equal original (chai)', function () {
    const type = avro.parse({
      name: 'Person',
      type: 'record',
      fields: [
        {name: 'id', type: 'int'},
        {name: 'first', type: 'string'},
        {name: 'last', type: 'string'}
      ]
    })
    const personBefore = {id: 1, first: 'bob', last: 'smith'}
    const buf = type.toBuffer(personBefore)
    const personAfter = type.fromBuffer(buf)

    chaiAssert.deepEqual(personAfter, personBefore)
  })

  it('encoded/decoded should deep equal original (assert)', function () {
    const type = avro.parse({
      name: 'Person',
      type: 'record',
      fields: [
        {name: 'id', type: 'int'},
        {name: 'first', type: 'string'},
        {name: 'last', type: 'string'}
      ]
    })
    const personBefore = {id: 1, first: 'bob', last: 'smith'}
    const buf = type.toBuffer(personBefore)
    const personAfter = type.fromBuffer(buf)

    assert.deepEqual(personAfter, personBefore)
  })
})
```

yields
```
 avsc
    1) encoded/decoded should deep equal original (chai)
    ✓ encoded/decoded should deep equal original (assert)


  1 passing (17ms)
  1 failing

  1) avsc encoded/decoded should deep equal original (chai):

      AssertionError: expected { Object (id, first, ...) } to deeply equal { id: 1, first: 'bob', last: 'smith' }
      + expected - actual

      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Context.<anonymous> (test/tests/avsc.test.js:23:16)
```

**Comment by mtth** [comment]
Indeed, it looks like [this is a known issue](https://github.com/chaijs/chai/issues/466).

I'm not sure this use-case is enough to add a "prototype stripping" method though. I'd recommend writing a small helper to copy the properties into a raw object, switching to another assert function, or perhaps extending the [`chai-avro`](https://www.npmjs.com/package/chai-avro) library.

If it's only for tests, you could also get away with `Object.setPrototypeOf(val, null)` (don't do this in production code, it'll [slow down your code](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/setPrototypeOf)).
