### ISSUE TITLE
Type reference failed

### ISSUE THREAD

**Issue by StarpTech** [mtth/avsc#83]
Hi 
i'm trying to reuse the type `Error` in nested propertys but I run into this issue. Thank you.

```js
const avro = require('avsc')

const type = avro.parse({
    name: 'Packet',
    type: 'record',
    fields: [
    {
        name: 'error',
        type: {
            name: 'Error',
            type: 'record',
            fields: [
                { name: 'name', type: 'string', default: '' },
                { name: 'code', type: 'int', 'default': -1},
                { name: 'message', type: 'string', default: '' },
                { name: 'cause', type: 'Error' }
            ]
        }
    }]
})

const buf = type.toBuffer({
    error: {}
})
const val = type.fromBuffer(buf)

console.log(val);

/*E:\Repositorys\avro-test>node .
undefined:4
  var v0 = v.name;
            ^

TypeError: Cannot read property 'name' of undefined
    at RecordType.writeError [as _write] (eval at RecordType._createWriter (E:\Repositorys\avro-test\node_modules\avsc\lib\types.js:2005:10), <anonymous>:4:13)
    at RecordType.writeError [as _write] (eval at RecordType._createWriter (E:\Repositorys\avro-test\node_modules\avsc\lib\types.js:2005:10), <anonymous>:22:6)
    at RecordType.writePacket [as _write] (eval at RecordType._createWriter (E:\Repositorys\avro-test\node_modules\avsc\lib\types.js:2005:10), <anonymous>:4:6)
    at RecordType.Type.toBuffer (E:\Repositorys\avro-test\node_modules\avsc\lib\types.js:317:8)
    at Object.<anonymous> (E:\Repositorys\avro-test\index.js:22:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)*/
```

**Comment by mtth** [comment]
`error`'s `cause` field has no default so passing in a empty object as `error` won't work (the `cause` field will be missing, hence the "name not found" error above). To avoid the infinite recursion, you probably want to make this field nullable as well. With you apply both these changes, everything should work as expected:

```javascript
const type = avro.parse({
    name: 'Packet',
    type: 'record',
    fields: [
    {
        name: 'error',
        type: {
            name: 'Error',
            type: 'record',
            fields: [
                { name: 'name', type: 'string', default: '' },
                { name: 'code', type: 'int', 'default': -1},
                { name: 'message', type: 'string', default: '' },
                { name: 'cause', type: ['null', 'Error'], default: null}
            ]
        }
    }]
});

const buf = type.toBuffer({error: {}});
const val = type.fromBuffer(buf);  // {error: {name: '', code: -1, message: '', cause: null}}

```

**Comment by StarpTech** [comment]
@mtth thanks!
